directoryserver_db_image:
  build: ./directoryServer/target/docker/database
  expose:
   - 5432
  container_name: dir-db

networkserver_db_image:
    build: ./networkServer/target/docker/database
    ports:
        - "5432:5432" 
    container_name: net-db

directoryserver_app_image:
  image: edex/directory-server
  volumes:
     - ./directoryServer/target:/opt/edexchange
  ports:
   - 8080:8080
   - 8443:8443
  environment:
   - SPRING_PROFILES_ACTIVE=${profile}
   - DB_SERVER=dir-db
   - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
   - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME}
   - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
  links:
   - directoryserver_db_image
  container_name: directory-app

networkserver_app_image:
  image: edex/network-server
  volumes:
     - ./networkServer/target:/opt/edexchange
  ports:
   - 8081:9000
   - 9443:9443
  environment:
   - SPRING_PROFILES_ACTIVE=${profile}
   - DB_SERVER=net-db
   - DIRECTORY_SERVER=localhost
   - DIRECTORY_SERVER_PORT=8080
  links:
   - networkserver_db_image
   - directoryserver_app_image
  container_name: network-app
