//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.cds.edexchange.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.UserDefinedExtensionsType;


/**
 * 
 *         ContentType Type (type of what's being sent)
 *       
 * 
 * <p>Java class for ContentTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContentCode" type="{urn:xmlns:EdExchange:v1.0.7}ContentCodeType"/>
 *         &lt;element name="ContentDescription" type="{urn:xmlns:EdExchange:v1.0.7}ContentDescriptionType" minOccurs="0"/>
 *         &lt;element name="ContentFileName" type="{urn:xmlns:EdExchange:v1.0.7}ContentFileNameType"/>
 *         &lt;element name="NoteMessageText" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensionsText" type="{urn:org:pesc:core:CoreMain:v1.12.0}UserDefinedExtensionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentTypeType", propOrder = {
    "contentCode",
    "contentDescription",
    "contentFileName",
    "noteMessageText",
    "userDefinedExtensionsText"
})
public class ContentTypeType {

    @XmlElement(name = "ContentCode", required = true)
    protected ContentCodeType contentCode;
    @XmlElement(name = "ContentDescription")
    protected String contentDescription;
    @XmlElement(name = "ContentFileName", required = true)
    protected String contentFileName;
    @XmlElement(name = "NoteMessageText")
    protected List<String> noteMessageText;
    @XmlElement(name = "UserDefinedExtensionsText")
    protected UserDefinedExtensionsType userDefinedExtensionsText;

    /**
     * Gets the value of the contentCode property.
     * 
     * @return
     *     possible object is
     *     {@link ContentCodeType }
     *     
     */
    public ContentCodeType getContentCode() {
        return contentCode;
    }

    /**
     * Sets the value of the contentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentCodeType }
     *     
     */
    public void setContentCode(ContentCodeType value) {
        this.contentCode = value;
    }

    /**
     * Gets the value of the contentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentDescription() {
        return contentDescription;
    }

    /**
     * Sets the value of the contentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentDescription(String value) {
        this.contentDescription = value;
    }

    /**
     * Gets the value of the contentFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentFileName() {
        return contentFileName;
    }

    /**
     * Sets the value of the contentFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentFileName(String value) {
        this.contentFileName = value;
    }

    /**
     * Gets the value of the noteMessageText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessageText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessageText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessageText() {
        if (noteMessageText == null) {
            noteMessageText = new ArrayList<String>();
        }
        return this.noteMessageText;
    }

    /**
     * Gets the value of the userDefinedExtensionsText property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensionsText() {
        return userDefinedExtensionsText;
    }

    /**
     * Sets the value of the userDefinedExtensionsText property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensionsText(UserDefinedExtensionsType value) {
        this.userDefinedExtensionsText = value;
    }

}
