//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.AcademicPredictionCodeType;


/**
 * Statistical predictions of success in school from the assessments and inventories
 * 
 * <p>Java class for AcademicPredictionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcademicPredictionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcademicPredictionCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicPredictionCodeType"/>
 *         &lt;element name="AcademicPredictionSubject" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicPredictionSubjectType"/>
 *         &lt;element name="AcademicPredictionValue" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}EducationTestScoresType"/>
 *         &lt;element name="AcademicPredictionInterpretation" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicPredictionInterpretationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcademicPredictionType", propOrder = {
    "academicPredictionCode",
    "academicPredictionSubject",
    "academicPredictionValue",
    "academicPredictionInterpretation"
})
public class AcademicPredictionType {

    @XmlElement(name = "AcademicPredictionCode", required = true)
    protected AcademicPredictionCodeType academicPredictionCode;
    @XmlElement(name = "AcademicPredictionSubject", required = true)
    protected String academicPredictionSubject;
    @XmlElement(name = "AcademicPredictionValue", required = true)
    protected EducationTestScoresType academicPredictionValue;
    @XmlElement(name = "AcademicPredictionInterpretation")
    protected String academicPredictionInterpretation;

    /**
     * Gets the value of the academicPredictionCode property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicPredictionCodeType }
     *     
     */
    public AcademicPredictionCodeType getAcademicPredictionCode() {
        return academicPredictionCode;
    }

    /**
     * Sets the value of the academicPredictionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicPredictionCodeType }
     *     
     */
    public void setAcademicPredictionCode(AcademicPredictionCodeType value) {
        this.academicPredictionCode = value;
    }

    /**
     * Gets the value of the academicPredictionSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcademicPredictionSubject() {
        return academicPredictionSubject;
    }

    /**
     * Sets the value of the academicPredictionSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcademicPredictionSubject(String value) {
        this.academicPredictionSubject = value;
    }

    /**
     * Gets the value of the academicPredictionValue property.
     * 
     * @return
     *     possible object is
     *     {@link EducationTestScoresType }
     *     
     */
    public EducationTestScoresType getAcademicPredictionValue() {
        return academicPredictionValue;
    }

    /**
     * Sets the value of the academicPredictionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationTestScoresType }
     *     
     */
    public void setAcademicPredictionValue(EducationTestScoresType value) {
        this.academicPredictionValue = value;
    }

    /**
     * Gets the value of the academicPredictionInterpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcademicPredictionInterpretation() {
        return academicPredictionInterpretation;
    }

    /**
     * Sets the value of the academicPredictionInterpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcademicPredictionInterpretation(String value) {
        this.academicPredictionInterpretation = value;
    }

}
