//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.AcademicHonorsType;
import org.pesc.core.coremain.v1_12.AcademicSummaryTypeType;
import org.pesc.core.coremain.v1_12.CourseCreditLevelType;
import org.pesc.core.coremain.v1_12.GPAType;
import org.pesc.core.coremain.v1_12.HighSchoolCreditSummaryType;
import org.pesc.core.coremain.v1_12.UserDefinedExtensionsType;


/**
 * Base type, only used as extension base
 * 
 * <p>Java class for AcademicSummaryBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcademicSummaryBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcademicSummaryType" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicSummaryTypeType" minOccurs="0"/>
 *         &lt;element name="AcademicSummaryLevel" type="{urn:org:pesc:core:CoreMain:v1.12.0}CourseCreditLevelType" minOccurs="0"/>
 *         &lt;element name="GPA" type="{urn:org:pesc:core:CoreMain:v1.12.0}GPAType" minOccurs="0"/>
 *         &lt;element name="AcademicHonors" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicHonorsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ClassRank" type="{urn:org:pesc:core:CoreMain:v1.12.0}ClassRankType" minOccurs="0"/>
 *         &lt;element name="ClassSize" type="{urn:org:pesc:core:CoreMain:v1.12.0}ClassSizeType" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.12.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HighSchoolCreditSummary" type="{urn:org:pesc:core:CoreMain:v1.12.0}HighSchoolCreditSummaryType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcademicSummaryBaseType", propOrder = {
    "academicSummaryType",
    "academicSummaryLevel",
    "gpa",
    "academicHonors",
    "classRank",
    "classSize",
    "userDefinedExtensions",
    "noteMessage",
    "highSchoolCreditSummary"
})
@XmlSeeAlso({
    AcademicSummaryE1Type.class,
    AcademicSummaryFType.class,
    AcademicSummaryE2Type.class
})
public class AcademicSummaryBaseType {

    @XmlElement(name = "AcademicSummaryType")
    protected AcademicSummaryTypeType academicSummaryType;
    @XmlElement(name = "AcademicSummaryLevel")
    protected CourseCreditLevelType academicSummaryLevel;
    @XmlElement(name = "GPA")
    protected GPAType gpa;
    @XmlElement(name = "AcademicHonors")
    protected List<AcademicHonorsType> academicHonors;
    @XmlElement(name = "ClassRank")
    protected Integer classRank;
    @XmlElement(name = "ClassSize")
    protected Integer classSize;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;
    @XmlElement(name = "HighSchoolCreditSummary")
    protected HighSchoolCreditSummaryType highSchoolCreditSummary;

    /**
     * Gets the value of the academicSummaryType property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicSummaryTypeType }
     *     
     */
    public AcademicSummaryTypeType getAcademicSummaryType() {
        return academicSummaryType;
    }

    /**
     * Sets the value of the academicSummaryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicSummaryTypeType }
     *     
     */
    public void setAcademicSummaryType(AcademicSummaryTypeType value) {
        this.academicSummaryType = value;
    }

    /**
     * Gets the value of the academicSummaryLevel property.
     * 
     * @return
     *     possible object is
     *     {@link CourseCreditLevelType }
     *     
     */
    public CourseCreditLevelType getAcademicSummaryLevel() {
        return academicSummaryLevel;
    }

    /**
     * Sets the value of the academicSummaryLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseCreditLevelType }
     *     
     */
    public void setAcademicSummaryLevel(CourseCreditLevelType value) {
        this.academicSummaryLevel = value;
    }

    /**
     * Gets the value of the gpa property.
     * 
     * @return
     *     possible object is
     *     {@link GPAType }
     *     
     */
    public GPAType getGPA() {
        return gpa;
    }

    /**
     * Sets the value of the gpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPAType }
     *     
     */
    public void setGPA(GPAType value) {
        this.gpa = value;
    }

    /**
     * Gets the value of the academicHonors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicHonors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicHonors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicHonorsType }
     * 
     * 
     */
    public List<AcademicHonorsType> getAcademicHonors() {
        if (academicHonors == null) {
            academicHonors = new ArrayList<AcademicHonorsType>();
        }
        return this.academicHonors;
    }

    /**
     * Gets the value of the classRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassRank() {
        return classRank;
    }

    /**
     * Sets the value of the classRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassRank(Integer value) {
        this.classRank = value;
    }

    /**
     * Gets the value of the classSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassSize() {
        return classSize;
    }

    /**
     * Sets the value of the classSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassSize(Integer value) {
        this.classSize = value;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

    /**
     * Gets the value of the highSchoolCreditSummary property.
     * 
     * @return
     *     possible object is
     *     {@link HighSchoolCreditSummaryType }
     *     
     */
    public HighSchoolCreditSummaryType getHighSchoolCreditSummary() {
        return highSchoolCreditSummary;
    }

    /**
     * Sets the value of the highSchoolCreditSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighSchoolCreditSummaryType }
     *     
     */
    public void setHighSchoolCreditSummary(HighSchoolCreditSummaryType value) {
        this.highSchoolCreditSummary = value;
    }

}
