//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_12.StudentLevelCodeType;


/**
 * Student accomplishments description 
 * 
 * <p>Java class for AdditionalStudentAchievementsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalStudentAchievementsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AchievementCategoryCode" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}AchievementCategoryCodeType" minOccurs="0"/>
 *         &lt;element name="AchievementTitle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Sponsor" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StudentLevelCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}StudentLevelCodeType" minOccurs="0"/>
 *         &lt;element name="AwardYear" type="{urn:org:pesc:core:CoreMain:v1.12.0}AwardYearType" minOccurs="0"/>
 *         &lt;element name="AwardYearMonth" type="{urn:org:pesc:core:CoreMain:v1.12.0}AwardYearMonthType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalStudentAchievementsType", propOrder = {
    "achievementCategoryCode",
    "achievementTitle",
    "sponsor",
    "studentLevelCode",
    "awardYear",
    "awardYearMonth",
    "noteMessage"
})
public class AdditionalStudentAchievementsType {

    @XmlElement(name = "AchievementCategoryCode")
    protected AchievementCategoryCodeType achievementCategoryCode;
    @XmlElement(name = "AchievementTitle")
    protected String achievementTitle;
    @XmlElement(name = "Sponsor")
    protected String sponsor;
    @XmlElement(name = "StudentLevelCode")
    protected StudentLevelCodeType studentLevelCode;
    @XmlElement(name = "AwardYear")
    protected XMLGregorianCalendar awardYear;
    @XmlElement(name = "AwardYearMonth")
    protected XMLGregorianCalendar awardYearMonth;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the achievementCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link AchievementCategoryCodeType }
     *     
     */
    public AchievementCategoryCodeType getAchievementCategoryCode() {
        return achievementCategoryCode;
    }

    /**
     * Sets the value of the achievementCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AchievementCategoryCodeType }
     *     
     */
    public void setAchievementCategoryCode(AchievementCategoryCodeType value) {
        this.achievementCategoryCode = value;
    }

    /**
     * Gets the value of the achievementTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAchievementTitle() {
        return achievementTitle;
    }

    /**
     * Sets the value of the achievementTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAchievementTitle(String value) {
        this.achievementTitle = value;
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSponsor() {
        return sponsor;
    }

    /**
     * Sets the value of the sponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSponsor(String value) {
        this.sponsor = value;
    }

    /**
     * Gets the value of the studentLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link StudentLevelCodeType }
     *     
     */
    public StudentLevelCodeType getStudentLevelCode() {
        return studentLevelCode;
    }

    /**
     * Sets the value of the studentLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentLevelCodeType }
     *     
     */
    public void setStudentLevelCode(StudentLevelCodeType value) {
        this.studentLevelCode = value;
    }

    /**
     * Gets the value of the awardYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAwardYear() {
        return awardYear;
    }

    /**
     * Sets the value of the awardYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAwardYear(XMLGregorianCalendar value) {
        this.awardYear = value;
    }

    /**
     * Gets the value of the awardYearMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAwardYearMonth() {
        return awardYearMonth;
    }

    /**
     * Sets the value of the awardYearMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAwardYearMonth(XMLGregorianCalendar value) {
        this.awardYearMonth = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
