//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AttendanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttendanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="School" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}SchoolType"/>
 *         &lt;element name="EnrollDate" type="{urn:org:pesc:core:CoreMain:v1.12.0}EnrollDateType" minOccurs="0"/>
 *         &lt;element name="ExitDate" type="{urn:org:pesc:core:CoreMain:v1.12.0}ExitDateType" minOccurs="0"/>
 *         &lt;element name="CurrentEnrollmentIndicator" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}CurrentEnrollmentIndicatorType" minOccurs="0"/>
 *         &lt;element name="AcademicAwardsReported" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}AcademicAwardsReportedType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttendanceType", propOrder = {
    "school",
    "enrollDate",
    "exitDate",
    "currentEnrollmentIndicator",
    "academicAwardsReported",
    "noteMessage"
})
public class AttendanceType {

    @XmlElement(name = "School", required = true)
    protected SchoolType school;
    @XmlElement(name = "EnrollDate")
    protected XMLGregorianCalendar enrollDate;
    @XmlElement(name = "ExitDate")
    protected XMLGregorianCalendar exitDate;
    @XmlElement(name = "CurrentEnrollmentIndicator")
    protected Boolean currentEnrollmentIndicator;
    @XmlElement(name = "AcademicAwardsReported")
    protected List<AcademicAwardsReportedType> academicAwardsReported;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolType }
     *     
     */
    public SchoolType getSchool() {
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolType }
     *     
     */
    public void setSchool(SchoolType value) {
        this.school = value;
    }

    /**
     * Gets the value of the enrollDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnrollDate() {
        return enrollDate;
    }

    /**
     * Sets the value of the enrollDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnrollDate(XMLGregorianCalendar value) {
        this.enrollDate = value;
    }

    /**
     * Gets the value of the exitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExitDate() {
        return exitDate;
    }

    /**
     * Sets the value of the exitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExitDate(XMLGregorianCalendar value) {
        this.exitDate = value;
    }

    /**
     * Gets the value of the currentEnrollmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCurrentEnrollmentIndicator() {
        return currentEnrollmentIndicator;
    }

    /**
     * Sets the value of the currentEnrollmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrentEnrollmentIndicator(Boolean value) {
        this.currentEnrollmentIndicator = value;
    }

    /**
     * Gets the value of the academicAwardsReported property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicAwardsReported property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicAwardsReported().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicAwardsReportedType }
     * 
     * 
     */
    public List<AcademicAwardsReportedType> getAcademicAwardsReported() {
        if (academicAwardsReported == null) {
            academicAwardsReported = new ArrayList<AcademicAwardsReportedType>();
        }
        return this.academicAwardsReported;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
