//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Named attribute value pairs with values being text, numbers or ranges
 * 
 * <p>Java class for CharacteristicsSelectionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacteristicsSelectionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CharacteristicName" type="{urn:org:pesc:core:CoreMain:v1.12.0}CharacteristicNameType"/>
 *         &lt;choice>
 *           &lt;element name="CharacteristicValue" type="{urn:org:pesc:core:CoreMain:v1.12.0}CharacteristicValueType"/>
 *           &lt;element name="CharacteristicRange" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}NumericRangeType"/>
 *           &lt;element name="SurveyQuestionValue" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}SurveyQuestionType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacteristicsSelectionsType", propOrder = {
    "characteristicName",
    "characteristicValue",
    "characteristicRange",
    "surveyQuestionValue"
})
public class CharacteristicsSelectionsType {

    @XmlElement(name = "CharacteristicName", required = true)
    protected String characteristicName;
    @XmlElement(name = "CharacteristicValue")
    protected String characteristicValue;
    @XmlElement(name = "CharacteristicRange")
    protected NumericRangeType characteristicRange;
    @XmlElement(name = "SurveyQuestionValue")
    protected SurveyQuestionType surveyQuestionValue;

    /**
     * Gets the value of the characteristicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacteristicName() {
        return characteristicName;
    }

    /**
     * Sets the value of the characteristicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacteristicName(String value) {
        this.characteristicName = value;
    }

    /**
     * Gets the value of the characteristicValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacteristicValue() {
        return characteristicValue;
    }

    /**
     * Sets the value of the characteristicValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacteristicValue(String value) {
        this.characteristicValue = value;
    }

    /**
     * Gets the value of the characteristicRange property.
     * 
     * @return
     *     possible object is
     *     {@link NumericRangeType }
     *     
     */
    public NumericRangeType getCharacteristicRange() {
        return characteristicRange;
    }

    /**
     * Sets the value of the characteristicRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericRangeType }
     *     
     */
    public void setCharacteristicRange(NumericRangeType value) {
        this.characteristicRange = value;
    }

    /**
     * Gets the value of the surveyQuestionValue property.
     * 
     * @return
     *     possible object is
     *     {@link SurveyQuestionType }
     *     
     */
    public SurveyQuestionType getSurveyQuestionValue() {
        return surveyQuestionValue;
    }

    /**
     * Sets the value of the surveyQuestionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurveyQuestionType }
     *     
     */
    public void setSurveyQuestionValue(SurveyQuestionType value) {
        this.surveyQuestionValue = value;
    }

}
