//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An assessment score that is expressed as an academic mark 
 * 
 * <p>Java class for CourseGradeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourseGradeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseAcademicGrade" type="{urn:org:pesc:core:CoreMain:v1.12.0}CourseAcademicGradeType"/>
 *         &lt;element name="CourseAcademicGradeScaleCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}CourseAcademicGradeScaleCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseGradeType", propOrder = {
    "courseAcademicGrade",
    "courseAcademicGradeScaleCode"
})
public class CourseGradeType {

    @XmlElement(name = "CourseAcademicGrade", required = true)
    protected String courseAcademicGrade;
    @XmlElement(name = "CourseAcademicGradeScaleCode")
    protected String courseAcademicGradeScaleCode;

    /**
     * Gets the value of the courseAcademicGrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseAcademicGrade() {
        return courseAcademicGrade;
    }

    /**
     * Sets the value of the courseAcademicGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseAcademicGrade(String value) {
        this.courseAcademicGrade = value;
    }

    /**
     * Gets the value of the courseAcademicGradeScaleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseAcademicGradeScaleCode() {
        return courseAcademicGradeScaleCode;
    }

    /**
     * Sets the value of the courseAcademicGradeScaleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseAcademicGradeScaleCode(String value) {
        this.courseAcademicGradeScaleCode = value;
    }

}
