//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeliveryMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HoldForPickup"/>
 *     &lt;enumeration value="Mail"/>
 *     &lt;enumeration value="Express"/>
 *     &lt;enumeration value="Overnight"/>
 *     &lt;enumeration value="Fax"/>
 *     &lt;enumeration value="FaxMail"/>
 *     &lt;enumeration value="FaxExpress"/>
 *     &lt;enumeration value="FaxOvernight"/>
 *     &lt;enumeration value="Electronic"/>
 *     &lt;enumeration value="ExpressInternational"/>
 *     &lt;enumeration value="ExpressCanadaMexico"/>
 *     &lt;enumeration value="ExpressUnitedStates"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeliveryMethodType")
@XmlEnum
public enum DeliveryMethodType {

    @XmlEnumValue("HoldForPickup")
    HOLD_FOR_PICKUP("HoldForPickup"),
    @XmlEnumValue("Mail")
    MAIL("Mail"),
    @XmlEnumValue("Express")
    EXPRESS("Express"),
    @XmlEnumValue("Overnight")
    OVERNIGHT("Overnight"),
    @XmlEnumValue("Fax")
    FAX("Fax"),
    @XmlEnumValue("FaxMail")
    FAX_MAIL("FaxMail"),
    @XmlEnumValue("FaxExpress")
    FAX_EXPRESS("FaxExpress"),
    @XmlEnumValue("FaxOvernight")
    FAX_OVERNIGHT("FaxOvernight"),
    @XmlEnumValue("Electronic")
    ELECTRONIC("Electronic"),
    @XmlEnumValue("ExpressInternational")
    EXPRESS_INTERNATIONAL("ExpressInternational"),
    @XmlEnumValue("ExpressCanadaMexico")
    EXPRESS_CANADA_MEXICO("ExpressCanadaMexico"),
    @XmlEnumValue("ExpressUnitedStates")
    EXPRESS_UNITED_STATES("ExpressUnitedStates");
    private final String value;

    DeliveryMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeliveryMethodType fromValue(String v) {
        for (DeliveryMethodType c: DeliveryMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
