//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.EducationSubtestCodeType;
import org.pesc.core.coremain.v1_12.ScoreExclusionReasonCodeType;


/**
 * The scored sections of an assessment
 * 
 * <p>Java class for EducationSubtestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EducationSubtestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EducationSubtestCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}EducationSubtestCodeType"/>
 *         &lt;element name="EducationSubtestName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScoreRevisedIndicator" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreRevisedIndicatorType" minOccurs="0"/>
 *         &lt;element name="ScoreInvalidatedIndicator" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreInvalidatedIndicatorType" minOccurs="0"/>
 *         &lt;element name="ScoreSelfreportedIndicator" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreSelfreportedIndicatorType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="ScoreExclusionReasonCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreExclusionReasonCodeType" maxOccurs="unbounded"/>
 *           &lt;element name="EducationTestScores" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}EducationTestScoresType"/>
 *         &lt;/choice>
 *         &lt;element name="Essay" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}EssayType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EducationSubtestType", propOrder = {
    "educationSubtestCode",
    "educationSubtestName",
    "scoreRevisedIndicator",
    "scoreInvalidatedIndicator",
    "scoreSelfreportedIndicator",
    "scoreExclusionReasonCode",
    "educationTestScores",
    "essay",
    "noteMessage"
})
public class EducationSubtestType {

    @XmlElement(name = "EducationSubtestCode", required = true)
    protected EducationSubtestCodeType educationSubtestCode;
    @XmlElement(name = "EducationSubtestName")
    protected String educationSubtestName;
    @XmlElement(name = "ScoreRevisedIndicator")
    protected Boolean scoreRevisedIndicator;
    @XmlElement(name = "ScoreInvalidatedIndicator")
    protected Boolean scoreInvalidatedIndicator;
    @XmlElement(name = "ScoreSelfreportedIndicator")
    protected Boolean scoreSelfreportedIndicator;
    @XmlElement(name = "ScoreExclusionReasonCode")
    protected List<ScoreExclusionReasonCodeType> scoreExclusionReasonCode;
    @XmlElement(name = "EducationTestScores")
    protected EducationTestScoresType educationTestScores;
    @XmlElement(name = "Essay")
    protected List<EssayType> essay;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the educationSubtestCode property.
     * 
     * @return
     *     possible object is
     *     {@link EducationSubtestCodeType }
     *     
     */
    public EducationSubtestCodeType getEducationSubtestCode() {
        return educationSubtestCode;
    }

    /**
     * Sets the value of the educationSubtestCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationSubtestCodeType }
     *     
     */
    public void setEducationSubtestCode(EducationSubtestCodeType value) {
        this.educationSubtestCode = value;
    }

    /**
     * Gets the value of the educationSubtestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducationSubtestName() {
        return educationSubtestName;
    }

    /**
     * Sets the value of the educationSubtestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducationSubtestName(String value) {
        this.educationSubtestName = value;
    }

    /**
     * Gets the value of the scoreRevisedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScoreRevisedIndicator() {
        return scoreRevisedIndicator;
    }

    /**
     * Sets the value of the scoreRevisedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScoreRevisedIndicator(Boolean value) {
        this.scoreRevisedIndicator = value;
    }

    /**
     * Gets the value of the scoreInvalidatedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScoreInvalidatedIndicator() {
        return scoreInvalidatedIndicator;
    }

    /**
     * Sets the value of the scoreInvalidatedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScoreInvalidatedIndicator(Boolean value) {
        this.scoreInvalidatedIndicator = value;
    }

    /**
     * Gets the value of the scoreSelfreportedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScoreSelfreportedIndicator() {
        return scoreSelfreportedIndicator;
    }

    /**
     * Sets the value of the scoreSelfreportedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScoreSelfreportedIndicator(Boolean value) {
        this.scoreSelfreportedIndicator = value;
    }

    /**
     * Gets the value of the scoreExclusionReasonCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scoreExclusionReasonCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScoreExclusionReasonCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreExclusionReasonCodeType }
     * 
     * 
     */
    public List<ScoreExclusionReasonCodeType> getScoreExclusionReasonCode() {
        if (scoreExclusionReasonCode == null) {
            scoreExclusionReasonCode = new ArrayList<ScoreExclusionReasonCodeType>();
        }
        return this.scoreExclusionReasonCode;
    }

    /**
     * Gets the value of the educationTestScores property.
     * 
     * @return
     *     possible object is
     *     {@link EducationTestScoresType }
     *     
     */
    public EducationTestScoresType getEducationTestScores() {
        return educationTestScores;
    }

    /**
     * Sets the value of the educationTestScores property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationTestScoresType }
     *     
     */
    public void setEducationTestScores(EducationTestScoresType value) {
        this.educationTestScores = value;
    }

    /**
     * Gets the value of the essay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the essay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEssay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EssayType }
     * 
     * 
     */
    public List<EssayType> getEssay() {
        if (essay == null) {
            essay = new ArrayList<EssayType>();
        }
        return this.essay;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
