//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtracurricularCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExtracurricularCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BoyScouts"/>
 *     &lt;enumeration value="Club4H"/>
 *     &lt;enumeration value="ClubArt"/>
 *     &lt;enumeration value="ClubCareer"/>
 *     &lt;enumeration value="ClubChess"/>
 *     &lt;enumeration value="ClubComputer"/>
 *     &lt;enumeration value="ClubDistributiveEducationAmerica"/>
 *     &lt;enumeration value="ClubDrama"/>
 *     &lt;enumeration value="ClubEnvironmental"/>
 *     &lt;enumeration value="ClubEthnic"/>
 *     &lt;enumeration value="ClubForeignLanguage"/>
 *     &lt;enumeration value="ClubFrench"/>
 *     &lt;enumeration value="ClubFutureBusinessLeadersAmerica"/>
 *     &lt;enumeration value="ClubFutureFarmersAmerica"/>
 *     &lt;enumeration value="ClubFutureHomemakersAmerica"/>
 *     &lt;enumeration value="ClubFutureTeachersAmerica"/>
 *     &lt;enumeration value="ClubGerman"/>
 *     &lt;enumeration value="ClubHealthOccupationsStudentsAmerica"/>
 *     &lt;enumeration value="ClubItalian"/>
 *     &lt;enumeration value="ClubLatin"/>
 *     &lt;enumeration value="ClubOther"/>
 *     &lt;enumeration value="ClubPortuguese"/>
 *     &lt;enumeration value="ClubRussian"/>
 *     &lt;enumeration value="ClubScience"/>
 *     &lt;enumeration value="ClubSpanish"/>
 *     &lt;enumeration value="ClubSpeechDebate"/>
 *     &lt;enumeration value="ClubStudentsAgainstDrunkDriving"/>
 *     &lt;enumeration value="Fraternity"/>
 *     &lt;enumeration value="GirlScouts"/>
 *     &lt;enumeration value="KeyClub"/>
 *     &lt;enumeration value="PeerCounseling"/>
 *     &lt;enumeration value="Sorority"/>
 *     &lt;enumeration value="Tutoring"/>
 *     &lt;enumeration value="AcademicHonorSociety"/>
 *     &lt;enumeration value="AcademicTeamBrainBowl"/>
 *     &lt;enumeration value="ClubBeta"/>
 *     &lt;enumeration value="ClubMuAlphaTheta"/>
 *     &lt;enumeration value="ClubPsiEtaScience"/>
 *     &lt;enumeration value="NationalForensicsLeague"/>
 *     &lt;enumeration value="NationalHonorSociety"/>
 *     &lt;enumeration value="ThespianSociety"/>
 *     &lt;enumeration value="Invention"/>
 *     &lt;enumeration value="Patent"/>
 *     &lt;enumeration value="Research"/>
 *     &lt;enumeration value="Broadcasting"/>
 *     &lt;enumeration value="Journalism"/>
 *     &lt;enumeration value="JournalismOther"/>
 *     &lt;enumeration value="LiteraryMagazine"/>
 *     &lt;enumeration value="YearBook"/>
 *     &lt;enumeration value="ClassOfficer"/>
 *     &lt;enumeration value="ClassPresident"/>
 *     &lt;enumeration value="StudentBodyOfficer"/>
 *     &lt;enumeration value="StudentBodyPresident"/>
 *     &lt;enumeration value="StudentLeadershipOther"/>
 *     &lt;enumeration value="ArtGraphicDesign"/>
 *     &lt;enumeration value="Band"/>
 *     &lt;enumeration value="Chorus"/>
 *     &lt;enumeration value="Dance"/>
 *     &lt;enumeration value="DanceTeam"/>
 *     &lt;enumeration value="DrillTeam"/>
 *     &lt;enumeration value="JazzEnsemble"/>
 *     &lt;enumeration value="MusicInstrumental"/>
 *     &lt;enumeration value="MusicOther"/>
 *     &lt;enumeration value="MusicTheoryComposition"/>
 *     &lt;enumeration value="MusicVocal"/>
 *     &lt;enumeration value="Orchestra"/>
 *     &lt;enumeration value="PerformingArtsOther"/>
 *     &lt;enumeration value="TheaterDrama"/>
 *     &lt;enumeration value="Dissertation"/>
 *     &lt;enumeration value="NovelBook"/>
 *     &lt;enumeration value="Poetry"/>
 *     &lt;enumeration value="ProfessionalPresentation"/>
 *     &lt;enumeration value="ProfessionalScholarlyArticle"/>
 *     &lt;enumeration value="ProseShortStory"/>
 *     &lt;enumeration value="PublicationOther"/>
 *     &lt;enumeration value="Textbook"/>
 *     &lt;enumeration value="Thesis"/>
 *     &lt;enumeration value="UnpublishedManuscript"/>
 *     &lt;enumeration value="Archery"/>
 *     &lt;enumeration value="Badminton"/>
 *     &lt;enumeration value="Baseball"/>
 *     &lt;enumeration value="Basketball"/>
 *     &lt;enumeration value="Bowling"/>
 *     &lt;enumeration value="Boxing"/>
 *     &lt;enumeration value="Cheerleading"/>
 *     &lt;enumeration value="Crew"/>
 *     &lt;enumeration value="CrossCountry"/>
 *     &lt;enumeration value="Diving"/>
 *     &lt;enumeration value="DivingScuba"/>
 *     &lt;enumeration value="Fencing"/>
 *     &lt;enumeration value="Football"/>
 *     &lt;enumeration value="Golf"/>
 *     &lt;enumeration value="Gymnastics"/>
 *     &lt;enumeration value="HandballTeam"/>
 *     &lt;enumeration value="HockeyField"/>
 *     &lt;enumeration value="HockeyIce"/>
 *     &lt;enumeration value="HorsebackRiding"/>
 *     &lt;enumeration value="Lacrosse"/>
 *     &lt;enumeration value="ManagerTeam"/>
 *     &lt;enumeration value="MartialArts"/>
 *     &lt;enumeration value="Polo"/>
 *     &lt;enumeration value="PoloWater"/>
 *     &lt;enumeration value="Racquetball"/>
 *     &lt;enumeration value="Riflery"/>
 *     &lt;enumeration value="Rodeo"/>
 *     &lt;enumeration value="Rugby"/>
 *     &lt;enumeration value="Sailing"/>
 *     &lt;enumeration value="Skiing"/>
 *     &lt;enumeration value="Soccer"/>
 *     &lt;enumeration value="Softball"/>
 *     &lt;enumeration value="SportOther"/>
 *     &lt;enumeration value="Squash"/>
 *     &lt;enumeration value="Swimming"/>
 *     &lt;enumeration value="SwimmingSynchronized"/>
 *     &lt;enumeration value="Tennis"/>
 *     &lt;enumeration value="TennisTable"/>
 *     &lt;enumeration value="TrackField"/>
 *     &lt;enumeration value="Volleyball"/>
 *     &lt;enumeration value="Wrestling"/>
 *     &lt;enumeration value="ChurchService"/>
 *     &lt;enumeration value="CommunityService"/>
 *     &lt;enumeration value="VolunteeringOther"/>
 *     &lt;enumeration value="VolunteerWork"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExtracurricularCodeType")
@XmlEnum
public enum ExtracurricularCodeType {

    @XmlEnumValue("BoyScouts")
    BOY_SCOUTS("BoyScouts"),
    @XmlEnumValue("Club4H")
    CLUB_4_H("Club4H"),
    @XmlEnumValue("ClubArt")
    CLUB_ART("ClubArt"),
    @XmlEnumValue("ClubCareer")
    CLUB_CAREER("ClubCareer"),
    @XmlEnumValue("ClubChess")
    CLUB_CHESS("ClubChess"),
    @XmlEnumValue("ClubComputer")
    CLUB_COMPUTER("ClubComputer"),
    @XmlEnumValue("ClubDistributiveEducationAmerica")
    CLUB_DISTRIBUTIVE_EDUCATION_AMERICA("ClubDistributiveEducationAmerica"),
    @XmlEnumValue("ClubDrama")
    CLUB_DRAMA("ClubDrama"),
    @XmlEnumValue("ClubEnvironmental")
    CLUB_ENVIRONMENTAL("ClubEnvironmental"),
    @XmlEnumValue("ClubEthnic")
    CLUB_ETHNIC("ClubEthnic"),
    @XmlEnumValue("ClubForeignLanguage")
    CLUB_FOREIGN_LANGUAGE("ClubForeignLanguage"),
    @XmlEnumValue("ClubFrench")
    CLUB_FRENCH("ClubFrench"),
    @XmlEnumValue("ClubFutureBusinessLeadersAmerica")
    CLUB_FUTURE_BUSINESS_LEADERS_AMERICA("ClubFutureBusinessLeadersAmerica"),
    @XmlEnumValue("ClubFutureFarmersAmerica")
    CLUB_FUTURE_FARMERS_AMERICA("ClubFutureFarmersAmerica"),
    @XmlEnumValue("ClubFutureHomemakersAmerica")
    CLUB_FUTURE_HOMEMAKERS_AMERICA("ClubFutureHomemakersAmerica"),
    @XmlEnumValue("ClubFutureTeachersAmerica")
    CLUB_FUTURE_TEACHERS_AMERICA("ClubFutureTeachersAmerica"),
    @XmlEnumValue("ClubGerman")
    CLUB_GERMAN("ClubGerman"),
    @XmlEnumValue("ClubHealthOccupationsStudentsAmerica")
    CLUB_HEALTH_OCCUPATIONS_STUDENTS_AMERICA("ClubHealthOccupationsStudentsAmerica"),
    @XmlEnumValue("ClubItalian")
    CLUB_ITALIAN("ClubItalian"),
    @XmlEnumValue("ClubLatin")
    CLUB_LATIN("ClubLatin"),
    @XmlEnumValue("ClubOther")
    CLUB_OTHER("ClubOther"),
    @XmlEnumValue("ClubPortuguese")
    CLUB_PORTUGUESE("ClubPortuguese"),
    @XmlEnumValue("ClubRussian")
    CLUB_RUSSIAN("ClubRussian"),
    @XmlEnumValue("ClubScience")
    CLUB_SCIENCE("ClubScience"),
    @XmlEnumValue("ClubSpanish")
    CLUB_SPANISH("ClubSpanish"),
    @XmlEnumValue("ClubSpeechDebate")
    CLUB_SPEECH_DEBATE("ClubSpeechDebate"),
    @XmlEnumValue("ClubStudentsAgainstDrunkDriving")
    CLUB_STUDENTS_AGAINST_DRUNK_DRIVING("ClubStudentsAgainstDrunkDriving"),
    @XmlEnumValue("Fraternity")
    FRATERNITY("Fraternity"),
    @XmlEnumValue("GirlScouts")
    GIRL_SCOUTS("GirlScouts"),
    @XmlEnumValue("KeyClub")
    KEY_CLUB("KeyClub"),
    @XmlEnumValue("PeerCounseling")
    PEER_COUNSELING("PeerCounseling"),
    @XmlEnumValue("Sorority")
    SORORITY("Sorority"),
    @XmlEnumValue("Tutoring")
    TUTORING("Tutoring"),
    @XmlEnumValue("AcademicHonorSociety")
    ACADEMIC_HONOR_SOCIETY("AcademicHonorSociety"),
    @XmlEnumValue("AcademicTeamBrainBowl")
    ACADEMIC_TEAM_BRAIN_BOWL("AcademicTeamBrainBowl"),
    @XmlEnumValue("ClubBeta")
    CLUB_BETA("ClubBeta"),
    @XmlEnumValue("ClubMuAlphaTheta")
    CLUB_MU_ALPHA_THETA("ClubMuAlphaTheta"),
    @XmlEnumValue("ClubPsiEtaScience")
    CLUB_PSI_ETA_SCIENCE("ClubPsiEtaScience"),
    @XmlEnumValue("NationalForensicsLeague")
    NATIONAL_FORENSICS_LEAGUE("NationalForensicsLeague"),
    @XmlEnumValue("NationalHonorSociety")
    NATIONAL_HONOR_SOCIETY("NationalHonorSociety"),
    @XmlEnumValue("ThespianSociety")
    THESPIAN_SOCIETY("ThespianSociety"),
    @XmlEnumValue("Invention")
    INVENTION("Invention"),
    @XmlEnumValue("Patent")
    PATENT("Patent"),
    @XmlEnumValue("Research")
    RESEARCH("Research"),
    @XmlEnumValue("Broadcasting")
    BROADCASTING("Broadcasting"),
    @XmlEnumValue("Journalism")
    JOURNALISM("Journalism"),
    @XmlEnumValue("JournalismOther")
    JOURNALISM_OTHER("JournalismOther"),
    @XmlEnumValue("LiteraryMagazine")
    LITERARY_MAGAZINE("LiteraryMagazine"),
    @XmlEnumValue("YearBook")
    YEAR_BOOK("YearBook"),
    @XmlEnumValue("ClassOfficer")
    CLASS_OFFICER("ClassOfficer"),
    @XmlEnumValue("ClassPresident")
    CLASS_PRESIDENT("ClassPresident"),
    @XmlEnumValue("StudentBodyOfficer")
    STUDENT_BODY_OFFICER("StudentBodyOfficer"),
    @XmlEnumValue("StudentBodyPresident")
    STUDENT_BODY_PRESIDENT("StudentBodyPresident"),
    @XmlEnumValue("StudentLeadershipOther")
    STUDENT_LEADERSHIP_OTHER("StudentLeadershipOther"),
    @XmlEnumValue("ArtGraphicDesign")
    ART_GRAPHIC_DESIGN("ArtGraphicDesign"),
    @XmlEnumValue("Band")
    BAND("Band"),
    @XmlEnumValue("Chorus")
    CHORUS("Chorus"),
    @XmlEnumValue("Dance")
    DANCE("Dance"),
    @XmlEnumValue("DanceTeam")
    DANCE_TEAM("DanceTeam"),
    @XmlEnumValue("DrillTeam")
    DRILL_TEAM("DrillTeam"),
    @XmlEnumValue("JazzEnsemble")
    JAZZ_ENSEMBLE("JazzEnsemble"),
    @XmlEnumValue("MusicInstrumental")
    MUSIC_INSTRUMENTAL("MusicInstrumental"),
    @XmlEnumValue("MusicOther")
    MUSIC_OTHER("MusicOther"),
    @XmlEnumValue("MusicTheoryComposition")
    MUSIC_THEORY_COMPOSITION("MusicTheoryComposition"),
    @XmlEnumValue("MusicVocal")
    MUSIC_VOCAL("MusicVocal"),
    @XmlEnumValue("Orchestra")
    ORCHESTRA("Orchestra"),
    @XmlEnumValue("PerformingArtsOther")
    PERFORMING_ARTS_OTHER("PerformingArtsOther"),
    @XmlEnumValue("TheaterDrama")
    THEATER_DRAMA("TheaterDrama"),
    @XmlEnumValue("Dissertation")
    DISSERTATION("Dissertation"),
    @XmlEnumValue("NovelBook")
    NOVEL_BOOK("NovelBook"),
    @XmlEnumValue("Poetry")
    POETRY("Poetry"),
    @XmlEnumValue("ProfessionalPresentation")
    PROFESSIONAL_PRESENTATION("ProfessionalPresentation"),
    @XmlEnumValue("ProfessionalScholarlyArticle")
    PROFESSIONAL_SCHOLARLY_ARTICLE("ProfessionalScholarlyArticle"),
    @XmlEnumValue("ProseShortStory")
    PROSE_SHORT_STORY("ProseShortStory"),
    @XmlEnumValue("PublicationOther")
    PUBLICATION_OTHER("PublicationOther"),
    @XmlEnumValue("Textbook")
    TEXTBOOK("Textbook"),
    @XmlEnumValue("Thesis")
    THESIS("Thesis"),
    @XmlEnumValue("UnpublishedManuscript")
    UNPUBLISHED_MANUSCRIPT("UnpublishedManuscript"),
    @XmlEnumValue("Archery")
    ARCHERY("Archery"),
    @XmlEnumValue("Badminton")
    BADMINTON("Badminton"),
    @XmlEnumValue("Baseball")
    BASEBALL("Baseball"),
    @XmlEnumValue("Basketball")
    BASKETBALL("Basketball"),
    @XmlEnumValue("Bowling")
    BOWLING("Bowling"),
    @XmlEnumValue("Boxing")
    BOXING("Boxing"),
    @XmlEnumValue("Cheerleading")
    CHEERLEADING("Cheerleading"),
    @XmlEnumValue("Crew")
    CREW("Crew"),
    @XmlEnumValue("CrossCountry")
    CROSS_COUNTRY("CrossCountry"),
    @XmlEnumValue("Diving")
    DIVING("Diving"),
    @XmlEnumValue("DivingScuba")
    DIVING_SCUBA("DivingScuba"),
    @XmlEnumValue("Fencing")
    FENCING("Fencing"),
    @XmlEnumValue("Football")
    FOOTBALL("Football"),
    @XmlEnumValue("Golf")
    GOLF("Golf"),
    @XmlEnumValue("Gymnastics")
    GYMNASTICS("Gymnastics"),
    @XmlEnumValue("HandballTeam")
    HANDBALL_TEAM("HandballTeam"),
    @XmlEnumValue("HockeyField")
    HOCKEY_FIELD("HockeyField"),
    @XmlEnumValue("HockeyIce")
    HOCKEY_ICE("HockeyIce"),
    @XmlEnumValue("HorsebackRiding")
    HORSEBACK_RIDING("HorsebackRiding"),
    @XmlEnumValue("Lacrosse")
    LACROSSE("Lacrosse"),
    @XmlEnumValue("ManagerTeam")
    MANAGER_TEAM("ManagerTeam"),
    @XmlEnumValue("MartialArts")
    MARTIAL_ARTS("MartialArts"),
    @XmlEnumValue("Polo")
    POLO("Polo"),
    @XmlEnumValue("PoloWater")
    POLO_WATER("PoloWater"),
    @XmlEnumValue("Racquetball")
    RACQUETBALL("Racquetball"),
    @XmlEnumValue("Riflery")
    RIFLERY("Riflery"),
    @XmlEnumValue("Rodeo")
    RODEO("Rodeo"),
    @XmlEnumValue("Rugby")
    RUGBY("Rugby"),
    @XmlEnumValue("Sailing")
    SAILING("Sailing"),
    @XmlEnumValue("Skiing")
    SKIING("Skiing"),
    @XmlEnumValue("Soccer")
    SOCCER("Soccer"),
    @XmlEnumValue("Softball")
    SOFTBALL("Softball"),
    @XmlEnumValue("SportOther")
    SPORT_OTHER("SportOther"),
    @XmlEnumValue("Squash")
    SQUASH("Squash"),
    @XmlEnumValue("Swimming")
    SWIMMING("Swimming"),
    @XmlEnumValue("SwimmingSynchronized")
    SWIMMING_SYNCHRONIZED("SwimmingSynchronized"),
    @XmlEnumValue("Tennis")
    TENNIS("Tennis"),
    @XmlEnumValue("TennisTable")
    TENNIS_TABLE("TennisTable"),
    @XmlEnumValue("TrackField")
    TRACK_FIELD("TrackField"),
    @XmlEnumValue("Volleyball")
    VOLLEYBALL("Volleyball"),
    @XmlEnumValue("Wrestling")
    WRESTLING("Wrestling"),
    @XmlEnumValue("ChurchService")
    CHURCH_SERVICE("ChurchService"),
    @XmlEnumValue("CommunityService")
    COMMUNITY_SERVICE("CommunityService"),
    @XmlEnumValue("VolunteeringOther")
    VOLUNTEERING_OTHER("VolunteeringOther"),
    @XmlEnumValue("VolunteerWork")
    VOLUNTEER_WORK("VolunteerWork");
    private final String value;

    ExtracurricularCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExtracurricularCodeType fromValue(String v) {
        for (ExtracurricularCodeType c: ExtracurricularCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
