//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.pesc.core.coremain.v1_12.AgencyIdentifierType;
import org.pesc.core.coremain.v1_12.DeceasedType;
import org.pesc.core.coremain.v1_12.EthnicityRaceType;
import org.pesc.core.coremain.v1_12.GenderType;
import org.pesc.core.coremain.v1_12.LanguageType;
import org.pesc.core.coremain.v1_12.NameType;
import org.pesc.core.coremain.v1_12.ParentGuardianType;
import org.pesc.core.coremain.v1_12.RaceEthnicityType;


/**
 * <p>Java class for K12PersonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="K12PersonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SchoolAssignedPersonID" type="{urn:org:pesc:core:CoreMain:v1.12.0}SchoolAssignedPersonIDType" minOccurs="0"/>
 *         &lt;element name="SIN" type="{urn:org:pesc:core:CoreMain:v1.12.0}SINIDType" minOccurs="0"/>
 *         &lt;element name="NSN" type="{urn:org:pesc:core:CoreMain:v1.12.0}NSNIDType" minOccurs="0"/>
 *         &lt;element name="AgencyAssignedID" type="{urn:org:pesc:core:CoreMain:v1.12.0}AgencyAssignedIDType" minOccurs="0"/>
 *         &lt;element name="AgencyIdentifier" type="{urn:org:pesc:core:CoreMain:v1.12.0}AgencyIdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RecipientAssignedID" type="{urn:org:pesc:core:CoreMain:v1.12.0}RecipientAssignedIDType" minOccurs="0"/>
 *         &lt;element name="SSN" type="{urn:org:pesc:core:CoreMain:v1.12.0}SSNType" minOccurs="0"/>
 *         &lt;element name="PartialSSN" type="{urn:org:pesc:core:CoreMain:v1.12.0}PartialSSNType" minOccurs="0"/>
 *         &lt;element name="Birth" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}BirthType" minOccurs="0"/>
 *         &lt;element name="Name" type="{urn:org:pesc:core:CoreMain:v1.12.0}NameType"/>
 *         &lt;element name="AlternateName" type="{urn:org:pesc:core:CoreMain:v1.12.0}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ParentGuardianName" type="{urn:org:pesc:core:CoreMain:v1.12.0}NameType" minOccurs="0"/>
 *         &lt;element name="ParentGuardian" type="{urn:org:pesc:core:CoreMain:v1.12.0}ParentGuardianType" minOccurs="0"/>
 *         &lt;element name="Contacts" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}ContactsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Gender" type="{urn:org:pesc:core:CoreMain:v1.12.0}GenderType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="RaceEthnicity" type="{urn:org:pesc:core:CoreMain:v1.12.0}RaceEthnicityType" minOccurs="0"/>
 *           &lt;element name="EthnicityRace" type="{urn:org:pesc:core:CoreMain:v1.12.0}EthnicityRaceType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Deceased" type="{urn:org:pesc:core:CoreMain:v1.12.0}DeceasedType" minOccurs="0"/>
 *         &lt;element name="Language" type="{urn:org:pesc:core:CoreMain:v1.12.0}LanguageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "K12PersonType", propOrder = {
    "schoolAssignedPersonID",
    "sin",
    "nsn",
    "agencyAssignedID",
    "agencyIdentifier",
    "recipientAssignedID",
    "ssn",
    "partialSSN",
    "birth",
    "name",
    "alternateName",
    "parentGuardianName",
    "parentGuardian",
    "contacts",
    "gender",
    "raceEthnicity",
    "ethnicityRace",
    "deceased",
    "language",
    "noteMessage"
})
public class K12PersonType {

    @XmlElement(name = "SchoolAssignedPersonID")
    protected String schoolAssignedPersonID;
    @XmlElement(name = "SIN")
    protected String sin;
    @XmlElement(name = "NSN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nsn;
    @XmlElement(name = "AgencyAssignedID")
    protected String agencyAssignedID;
    @XmlElement(name = "AgencyIdentifier")
    protected List<AgencyIdentifierType> agencyIdentifier;
    @XmlElement(name = "RecipientAssignedID")
    protected String recipientAssignedID;
    @XmlElement(name = "SSN")
    protected String ssn;
    @XmlElement(name = "PartialSSN")
    protected String partialSSN;
    @XmlElement(name = "Birth")
    protected BirthType birth;
    @XmlElement(name = "Name", required = true)
    protected NameType name;
    @XmlElement(name = "AlternateName")
    protected List<NameType> alternateName;
    @XmlElement(name = "ParentGuardianName")
    protected NameType parentGuardianName;
    @XmlElement(name = "ParentGuardian")
    protected ParentGuardianType parentGuardian;
    @XmlElement(name = "Contacts")
    protected List<ContactsType> contacts;
    @XmlElement(name = "Gender")
    protected GenderType gender;
    @XmlElement(name = "RaceEthnicity")
    protected RaceEthnicityType raceEthnicity;
    @XmlElement(name = "EthnicityRace")
    protected EthnicityRaceType ethnicityRace;
    @XmlElement(name = "Deceased")
    protected DeceasedType deceased;
    @XmlElement(name = "Language")
    protected List<LanguageType> language;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the schoolAssignedPersonID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolAssignedPersonID() {
        return schoolAssignedPersonID;
    }

    /**
     * Sets the value of the schoolAssignedPersonID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolAssignedPersonID(String value) {
        this.schoolAssignedPersonID = value;
    }

    /**
     * Gets the value of the sin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIN() {
        return sin;
    }

    /**
     * Sets the value of the sin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIN(String value) {
        this.sin = value;
    }

    /**
     * Gets the value of the nsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNSN() {
        return nsn;
    }

    /**
     * Sets the value of the nsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNSN(String value) {
        this.nsn = value;
    }

    /**
     * Gets the value of the agencyAssignedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencyAssignedID() {
        return agencyAssignedID;
    }

    /**
     * Sets the value of the agencyAssignedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencyAssignedID(String value) {
        this.agencyAssignedID = value;
    }

    /**
     * Gets the value of the agencyIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agencyIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgencyIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgencyIdentifierType }
     * 
     * 
     */
    public List<AgencyIdentifierType> getAgencyIdentifier() {
        if (agencyIdentifier == null) {
            agencyIdentifier = new ArrayList<AgencyIdentifierType>();
        }
        return this.agencyIdentifier;
    }

    /**
     * Gets the value of the recipientAssignedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientAssignedID() {
        return recipientAssignedID;
    }

    /**
     * Sets the value of the recipientAssignedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientAssignedID(String value) {
        this.recipientAssignedID = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the partialSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialSSN() {
        return partialSSN;
    }

    /**
     * Sets the value of the partialSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialSSN(String value) {
        this.partialSSN = value;
    }

    /**
     * Gets the value of the birth property.
     * 
     * @return
     *     possible object is
     *     {@link BirthType }
     *     
     */
    public BirthType getBirth() {
        return birth;
    }

    /**
     * Sets the value of the birth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthType }
     *     
     */
    public void setBirth(BirthType value) {
        this.birth = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setName(NameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the alternateName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getAlternateName() {
        if (alternateName == null) {
            alternateName = new ArrayList<NameType>();
        }
        return this.alternateName;
    }

    /**
     * Gets the value of the parentGuardianName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getParentGuardianName() {
        return parentGuardianName;
    }

    /**
     * Sets the value of the parentGuardianName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setParentGuardianName(NameType value) {
        this.parentGuardianName = value;
    }

    /**
     * Gets the value of the parentGuardian property.
     * 
     * @return
     *     possible object is
     *     {@link ParentGuardianType }
     *     
     */
    public ParentGuardianType getParentGuardian() {
        return parentGuardian;
    }

    /**
     * Sets the value of the parentGuardian property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentGuardianType }
     *     
     */
    public void setParentGuardian(ParentGuardianType value) {
        this.parentGuardian = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactsType }
     * 
     * 
     */
    public List<ContactsType> getContacts() {
        if (contacts == null) {
            contacts = new ArrayList<ContactsType>();
        }
        return this.contacts;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderType }
     *     
     */
    public GenderType getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderType }
     *     
     */
    public void setGender(GenderType value) {
        this.gender = value;
    }

    /**
     * Gets the value of the raceEthnicity property.
     * 
     * @return
     *     possible object is
     *     {@link RaceEthnicityType }
     *     
     */
    public RaceEthnicityType getRaceEthnicity() {
        return raceEthnicity;
    }

    /**
     * Sets the value of the raceEthnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceEthnicityType }
     *     
     */
    public void setRaceEthnicity(RaceEthnicityType value) {
        this.raceEthnicity = value;
    }

    /**
     * Gets the value of the ethnicityRace property.
     * 
     * @return
     *     possible object is
     *     {@link EthnicityRaceType }
     *     
     */
    public EthnicityRaceType getEthnicityRace() {
        return ethnicityRace;
    }

    /**
     * Sets the value of the ethnicityRace property.
     * 
     * @param value
     *     allowed object is
     *     {@link EthnicityRaceType }
     *     
     */
    public void setEthnicityRace(EthnicityRaceType value) {
        this.ethnicityRace = value;
    }

    /**
     * Gets the value of the deceased property.
     * 
     * @return
     *     possible object is
     *     {@link DeceasedType }
     *     
     */
    public DeceasedType getDeceased() {
        return deceased;
    }

    /**
     * Sets the value of the deceased property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeceasedType }
     *     
     */
    public void setDeceased(DeceasedType value) {
        this.deceased = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguageType }
     * 
     * 
     */
    public List<LanguageType> getLanguage() {
        if (language == null) {
            language = new ArrayList<LanguageType>();
        }
        return this.language;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
