//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A maximum and minimum value with inclusion or exclusion
 * 
 * <p>Java class for NumericRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumericRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumericLowerBound" type="{urn:org:pesc:core:CoreMain:v1.12.0}NumericLowerBoundType"/>
 *         &lt;element name="NumericUpperBound" type="{urn:org:pesc:core:CoreMain:v1.12.0}NumericUpperBoundType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumericRangeType", propOrder = {
    "numericLowerBound",
    "numericUpperBound"
})
public class NumericRangeType {

    @XmlElement(name = "NumericLowerBound", required = true, nillable = true)
    protected BigDecimal numericLowerBound;
    @XmlElement(name = "NumericUpperBound", required = true, nillable = true)
    protected BigDecimal numericUpperBound;

    /**
     * Gets the value of the numericLowerBound property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumericLowerBound() {
        return numericLowerBound;
    }

    /**
     * Sets the value of the numericLowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumericLowerBound(BigDecimal value) {
        this.numericLowerBound = value;
    }

    /**
     * Gets the value of the numericUpperBound property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumericUpperBound() {
        return numericUpperBound;
    }

    /**
     * Sets the value of the numericUpperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumericUpperBound(BigDecimal value) {
        this.numericUpperBound = value;
    }

}
