//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponseStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TranscriptSent"/>
 *     &lt;enumeration value="TranscriptRequestReceived"/>
 *     &lt;enumeration value="Hold"/>
 *     &lt;enumeration value="NoRecord"/>
 *     &lt;enumeration value="MultipleMatch"/>
 *     &lt;enumeration value="Canceled"/>
 *     &lt;enumeration value="OfflineRecordSearch"/>
 *     &lt;enumeration value="OfflineRecordSent"/>
 *     &lt;enumeration value="Deceased"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResponseStatusType")
@XmlEnum
public enum ResponseStatusType {

    @XmlEnumValue("TranscriptSent")
    TRANSCRIPT_SENT("TranscriptSent"),
    @XmlEnumValue("TranscriptRequestReceived")
    TRANSCRIPT_REQUEST_RECEIVED("TranscriptRequestReceived"),
    @XmlEnumValue("Hold")
    HOLD("Hold"),
    @XmlEnumValue("NoRecord")
    NO_RECORD("NoRecord"),
    @XmlEnumValue("MultipleMatch")
    MULTIPLE_MATCH("MultipleMatch"),
    @XmlEnumValue("Canceled")
    CANCELED("Canceled"),
    @XmlEnumValue("OfflineRecordSearch")
    OFFLINE_RECORD_SEARCH("OfflineRecordSearch"),
    @XmlEnumValue("OfflineRecordSent")
    OFFLINE_RECORD_SENT("OfflineRecordSent"),
    @XmlEnumValue("Deceased")
    DECEASED("Deceased");
    private final String value;

    ResponseStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResponseStatusType fromValue(String v) {
        for (ResponseStatusType c: ResponseStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
