//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.CourseStatusCodeType;


/**
 * Subjects and grades as summarized by the student
 * 
 * <p>Java class for SelfReportedCourseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelfReportedCourseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseTitle" type="{urn:org:pesc:core:CoreMain:v1.12.0}CourseTitleType"/>
 *         &lt;element name="CourseGrade" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}CourseGradeType" minOccurs="0"/>
 *         &lt;element name="CourseStatusCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}CourseStatusCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelfReportedCourseType", propOrder = {
    "courseTitle",
    "courseGrade",
    "courseStatusCode"
})
public class SelfReportedCourseType {

    @XmlElement(name = "CourseTitle", required = true)
    protected String courseTitle;
    @XmlElement(name = "CourseGrade")
    protected CourseGradeType courseGrade;
    @XmlElement(name = "CourseStatusCode", required = true)
    protected CourseStatusCodeType courseStatusCode;

    /**
     * Gets the value of the courseTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * Sets the value of the courseTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseTitle(String value) {
        this.courseTitle = value;
    }

    /**
     * Gets the value of the courseGrade property.
     * 
     * @return
     *     possible object is
     *     {@link CourseGradeType }
     *     
     */
    public CourseGradeType getCourseGrade() {
        return courseGrade;
    }

    /**
     * Sets the value of the courseGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseGradeType }
     *     
     */
    public void setCourseGrade(CourseGradeType value) {
        this.courseGrade = value;
    }

    /**
     * Gets the value of the courseStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CourseStatusCodeType }
     *     
     */
    public CourseStatusCodeType getCourseStatusCode() {
        return courseStatusCode;
    }

    /**
     * Sets the value of the courseStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseStatusCodeType }
     *     
     */
    public void setCourseStatusCode(CourseStatusCodeType value) {
        this.courseStatusCode = value;
    }

}
