//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.SponsorTypeType;


/**
 * <p>Java class for SponsorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SponsorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SponsorOrganization" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}OrganizationType" minOccurs="0"/>
 *         &lt;element name="SponsorPerson" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}PersonType" minOccurs="0"/>
 *         &lt;element name="SponsorType" type="{urn:org:pesc:core:CoreMain:v1.12.0}SponsorTypeType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SponsorType", propOrder = {
    "sponsorOrganization",
    "sponsorPerson",
    "sponsorType",
    "noteMessage"
})
public class SponsorType {

    @XmlElement(name = "SponsorOrganization")
    protected OrganizationType sponsorOrganization;
    @XmlElement(name = "SponsorPerson")
    protected PersonType sponsorPerson;
    @XmlElement(name = "SponsorType")
    protected SponsorTypeType sponsorType;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the sponsorOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *     
     */
    public OrganizationType getSponsorOrganization() {
        return sponsorOrganization;
    }

    /**
     * Sets the value of the sponsorOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *     
     */
    public void setSponsorOrganization(OrganizationType value) {
        this.sponsorOrganization = value;
    }

    /**
     * Gets the value of the sponsorPerson property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getSponsorPerson() {
        return sponsorPerson;
    }

    /**
     * Sets the value of the sponsorPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setSponsorPerson(PersonType value) {
        this.sponsorPerson = value;
    }

    /**
     * Gets the value of the sponsorType property.
     * 
     * @return
     *     possible object is
     *     {@link SponsorTypeType }
     *     
     */
    public SponsorTypeType getSponsorType() {
        return sponsorType;
    }

    /**
     * Sets the value of the sponsorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SponsorTypeType }
     *     
     */
    public void setSponsorType(SponsorTypeType value) {
        this.sponsorType = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
