//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.UserDefinedExtensionsType;


/**
 * Information including student characteristics, academic history and test scores
 * 
 * <p>Java class for TestStudentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestStudentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TestPerson" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}TestPersonType"/>
 *         &lt;element name="AcademicRecord" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}AcademicRecordType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SelfReportedAcademicRecord" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}SelfReportedAcademicRecordType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StudentActivities" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}StudentActivitiesType" minOccurs="0"/>
 *         &lt;element name="SchoolSelectionCriteria" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}SchoolSelectionCriteriaType" minOccurs="0"/>
 *         &lt;element name="EducationTests" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}EducationTestsType" maxOccurs="unbounded"/>
 *         &lt;element name="AcademicPrediction" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}AcademicPredictionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdditionalStudentCharacteristics" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}CharacteristicsSelectionsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.12.0}UserDefinedExtensionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestStudentType", propOrder = {
    "testPerson",
    "academicRecord",
    "selfReportedAcademicRecord",
    "studentActivities",
    "schoolSelectionCriteria",
    "educationTests",
    "academicPrediction",
    "additionalStudentCharacteristics",
    "noteMessage",
    "userDefinedExtensions"
})
public class TestStudentType {

    @XmlElement(name = "TestPerson", required = true)
    protected TestPersonType testPerson;
    @XmlElement(name = "AcademicRecord")
    protected List<AcademicRecordType> academicRecord;
    @XmlElement(name = "SelfReportedAcademicRecord")
    protected List<SelfReportedAcademicRecordType> selfReportedAcademicRecord;
    @XmlElement(name = "StudentActivities")
    protected StudentActivitiesType studentActivities;
    @XmlElement(name = "SchoolSelectionCriteria")
    protected SchoolSelectionCriteriaType schoolSelectionCriteria;
    @XmlElement(name = "EducationTests", required = true)
    protected List<EducationTestsType> educationTests;
    @XmlElement(name = "AcademicPrediction")
    protected List<AcademicPredictionType> academicPrediction;
    @XmlElement(name = "AdditionalStudentCharacteristics")
    protected List<CharacteristicsSelectionsType> additionalStudentCharacteristics;
    @XmlElement(name = "NoteMessage")
    protected String noteMessage;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;

    /**
     * Gets the value of the testPerson property.
     * 
     * @return
     *     possible object is
     *     {@link TestPersonType }
     *     
     */
    public TestPersonType getTestPerson() {
        return testPerson;
    }

    /**
     * Sets the value of the testPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestPersonType }
     *     
     */
    public void setTestPerson(TestPersonType value) {
        this.testPerson = value;
    }

    /**
     * Gets the value of the academicRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicRecordType }
     * 
     * 
     */
    public List<AcademicRecordType> getAcademicRecord() {
        if (academicRecord == null) {
            academicRecord = new ArrayList<AcademicRecordType>();
        }
        return this.academicRecord;
    }

    /**
     * Gets the value of the selfReportedAcademicRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfReportedAcademicRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfReportedAcademicRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelfReportedAcademicRecordType }
     * 
     * 
     */
    public List<SelfReportedAcademicRecordType> getSelfReportedAcademicRecord() {
        if (selfReportedAcademicRecord == null) {
            selfReportedAcademicRecord = new ArrayList<SelfReportedAcademicRecordType>();
        }
        return this.selfReportedAcademicRecord;
    }

    /**
     * Gets the value of the studentActivities property.
     * 
     * @return
     *     possible object is
     *     {@link StudentActivitiesType }
     *     
     */
    public StudentActivitiesType getStudentActivities() {
        return studentActivities;
    }

    /**
     * Sets the value of the studentActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentActivitiesType }
     *     
     */
    public void setStudentActivities(StudentActivitiesType value) {
        this.studentActivities = value;
    }

    /**
     * Gets the value of the schoolSelectionCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolSelectionCriteriaType }
     *     
     */
    public SchoolSelectionCriteriaType getSchoolSelectionCriteria() {
        return schoolSelectionCriteria;
    }

    /**
     * Sets the value of the schoolSelectionCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolSelectionCriteriaType }
     *     
     */
    public void setSchoolSelectionCriteria(SchoolSelectionCriteriaType value) {
        this.schoolSelectionCriteria = value;
    }

    /**
     * Gets the value of the educationTests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the educationTests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEducationTests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EducationTestsType }
     * 
     * 
     */
    public List<EducationTestsType> getEducationTests() {
        if (educationTests == null) {
            educationTests = new ArrayList<EducationTestsType>();
        }
        return this.educationTests;
    }

    /**
     * Gets the value of the academicPrediction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicPrediction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicPrediction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicPredictionType }
     * 
     * 
     */
    public List<AcademicPredictionType> getAcademicPrediction() {
        if (academicPrediction == null) {
            academicPrediction = new ArrayList<AcademicPredictionType>();
        }
        return this.academicPrediction;
    }

    /**
     * Gets the value of the additionalStudentCharacteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalStudentCharacteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalStudentCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharacteristicsSelectionsType }
     * 
     * 
     */
    public List<CharacteristicsSelectionsType> getAdditionalStudentCharacteristics() {
        if (additionalStudentCharacteristics == null) {
            additionalStudentCharacteristics = new ArrayList<CharacteristicsSelectionsType>();
        }
        return this.additionalStudentCharacteristics;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteMessage() {
        return noteMessage;
    }

    /**
     * Sets the value of the noteMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteMessage(String value) {
        this.noteMessage = value;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

}
