//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.sector.academicrecord.v1_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_12.UserDefinedExtensionsType;


/**
 * Informaiton about the attribuites, accomplishments and test scores of a set of students
 * 
 * <p>Java class for TestScoreReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestScoreReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransmissionData" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}TransmissionDataType"/>
 *         &lt;element name="TestStudent" type="{urn:org:pesc:sector:AcademicRecord:v1.7.0}TestStudentType" maxOccurs="unbounded"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.12.0}UserDefinedExtensionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestScoreReportType", propOrder = {
    "transmissionData",
    "testStudent",
    "noteMessage",
    "userDefinedExtensions"
})
public class TestScoreReportType {

    @XmlElement(name = "TransmissionData", required = true)
    protected TransmissionDataType transmissionData;
    @XmlElement(name = "TestStudent", required = true)
    protected List<TestStudentType> testStudent;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;

    /**
     * Gets the value of the transmissionData property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionDataType }
     *     
     */
    public TransmissionDataType getTransmissionData() {
        return transmissionData;
    }

    /**
     * Sets the value of the transmissionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionDataType }
     *     
     */
    public void setTransmissionData(TransmissionDataType value) {
        this.transmissionData = value;
    }

    /**
     * Gets the value of the testStudent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testStudent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestStudent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestStudentType }
     * 
     * 
     */
    public List<TestStudentType> getTestStudent() {
        if (testStudent == null) {
            testStudent = new ArrayList<TestStudentType>();
        }
        return this.testStudent;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

}
