//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcademicProgramDegreeLevelCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AcademicProgramDegreeLevelCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AssociateDegree"/>
 *     &lt;enumeration value="BaccalaureateDegree"/>
 *     &lt;enumeration value="Certificate"/>
 *     &lt;enumeration value="Doctorate"/>
 *     &lt;enumeration value="GraduateDegree"/>
 *     &lt;enumeration value="HighSchool"/>
 *     &lt;enumeration value="MastersDegree"/>
 *     &lt;enumeration value="NonDegree"/>
 *     &lt;enumeration value="PostBaccalaureateCertificate"/>
 *     &lt;enumeration value="PostsecondaryDiploma"/>
 *     &lt;enumeration value="ProfessionalDegree"/>
 *     &lt;enumeration value="UndergraduateCertificate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AcademicProgramDegreeLevelCodeType")
@XmlEnum
public enum AcademicProgramDegreeLevelCodeType {

    @XmlEnumValue("AssociateDegree")
    ASSOCIATE_DEGREE("AssociateDegree"),
    @XmlEnumValue("BaccalaureateDegree")
    BACCALAUREATE_DEGREE("BaccalaureateDegree"),
    @XmlEnumValue("Certificate")
    CERTIFICATE("Certificate"),
    @XmlEnumValue("Doctorate")
    DOCTORATE("Doctorate"),
    @XmlEnumValue("GraduateDegree")
    GRADUATE_DEGREE("GraduateDegree"),
    @XmlEnumValue("HighSchool")
    HIGH_SCHOOL("HighSchool"),
    @XmlEnumValue("MastersDegree")
    MASTERS_DEGREE("MastersDegree"),
    @XmlEnumValue("NonDegree")
    NON_DEGREE("NonDegree"),
    @XmlEnumValue("PostBaccalaureateCertificate")
    POST_BACCALAUREATE_CERTIFICATE("PostBaccalaureateCertificate"),
    @XmlEnumValue("PostsecondaryDiploma")
    POSTSECONDARY_DIPLOMA("PostsecondaryDiploma"),
    @XmlEnumValue("ProfessionalDegree")
    PROFESSIONAL_DEGREE("ProfessionalDegree"),
    @XmlEnumValue("UndergraduateCertificate")
    UNDERGRADUATE_CERTIFICATE("UndergraduateCertificate");
    private final String value;

    AcademicProgramDegreeLevelCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AcademicProgramDegreeLevelCodeType fromValue(String v) {
        for (AcademicProgramDegreeLevelCodeType c: AcademicProgramDegreeLevelCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
