//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcademicProgramType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcademicProgramType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicProgramCodeGroup" minOccurs="0"/>
 *         &lt;element name="AcademicProgramType" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicProgramTypeType" minOccurs="0"/>
 *         &lt;element name="AcademicProgramName" type="{urn:org:pesc:core:CoreMain:v1.12.0}AcademicProgramNameType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcademicProgramType", propOrder = {
    "programSecondarySchoolCode",
    "programCIPCode",
    "programHEGISCode",
    "programCSISCode",
    "programUSISCode",
    "programESISCode",
    "programLocalCode",
    "academicProgramType",
    "academicProgramName",
    "noteMessage"
})
@XmlSeeAlso({
    org.pesc.sector.academicrecord.v1_7.AcademicProgramType.class
})
public class AcademicProgramType {

    @XmlElement(name = "ProgramSecondarySchoolCode")
    protected ProgramSecondarySchoolCodeType programSecondarySchoolCode;
    @XmlElement(name = "ProgramCIPCode")
    protected String programCIPCode;
    @XmlElement(name = "ProgramHEGISCode")
    protected String programHEGISCode;
    @XmlElement(name = "ProgramCSISCode")
    protected String programCSISCode;
    @XmlElement(name = "ProgramUSISCode")
    protected String programUSISCode;
    @XmlElement(name = "ProgramESISCode")
    protected String programESISCode;
    @XmlElement(name = "ProgramLocalCode")
    protected String programLocalCode;
    @XmlElement(name = "AcademicProgramType")
    protected AcademicProgramTypeType academicProgramType;
    @XmlElement(name = "AcademicProgramName")
    protected String academicProgramName;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the programSecondarySchoolCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramSecondarySchoolCodeType }
     *     
     */
    public ProgramSecondarySchoolCodeType getProgramSecondarySchoolCode() {
        return programSecondarySchoolCode;
    }

    /**
     * Sets the value of the programSecondarySchoolCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramSecondarySchoolCodeType }
     *     
     */
    public void setProgramSecondarySchoolCode(ProgramSecondarySchoolCodeType value) {
        this.programSecondarySchoolCode = value;
    }

    /**
     * Gets the value of the programCIPCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramCIPCode() {
        return programCIPCode;
    }

    /**
     * Sets the value of the programCIPCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramCIPCode(String value) {
        this.programCIPCode = value;
    }

    /**
     * Gets the value of the programHEGISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramHEGISCode() {
        return programHEGISCode;
    }

    /**
     * Sets the value of the programHEGISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramHEGISCode(String value) {
        this.programHEGISCode = value;
    }

    /**
     * Gets the value of the programCSISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramCSISCode() {
        return programCSISCode;
    }

    /**
     * Sets the value of the programCSISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramCSISCode(String value) {
        this.programCSISCode = value;
    }

    /**
     * Gets the value of the programUSISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramUSISCode() {
        return programUSISCode;
    }

    /**
     * Sets the value of the programUSISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramUSISCode(String value) {
        this.programUSISCode = value;
    }

    /**
     * Gets the value of the programESISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramESISCode() {
        return programESISCode;
    }

    /**
     * Sets the value of the programESISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramESISCode(String value) {
        this.programESISCode = value;
    }

    /**
     * Gets the value of the programLocalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramLocalCode() {
        return programLocalCode;
    }

    /**
     * Sets the value of the programLocalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramLocalCode(String value) {
        this.programLocalCode = value;
    }

    /**
     * Gets the value of the academicProgramType property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicProgramTypeType }
     *     
     */
    public AcademicProgramTypeType getAcademicProgramType() {
        return academicProgramType;
    }

    /**
     * Sets the value of the academicProgramType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicProgramTypeType }
     *     
     */
    public void setAcademicProgramType(AcademicProgramTypeType value) {
        this.academicProgramType = value;
    }

    /**
     * Gets the value of the academicProgramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcademicProgramName() {
        return academicProgramName;
    }

    /**
     * Sets the value of the academicProgramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcademicProgramName(String value) {
        this.academicProgramName = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
