//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdmissionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AdmissionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Provisional"/>
 *     &lt;enumeration value="Developmental"/>
 *     &lt;enumeration value="Regular"/>
 *     &lt;enumeration value="Deferred"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AdmissionTypeType")
@XmlEnum
public enum AdmissionTypeType {

    @XmlEnumValue("Provisional")
    PROVISIONAL("Provisional"),
    @XmlEnumValue("Developmental")
    DEVELOPMENTAL("Developmental"),
    @XmlEnumValue("Regular")
    REGULAR("Regular"),
    @XmlEnumValue("Deferred")
    DEFERRED("Deferred"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    AdmissionTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AdmissionTypeType fromValue(String v) {
        for (AdmissionTypeType c: AdmissionTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
