//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgencyCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AgencyCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="District"/>
 *     &lt;enumeration value="Migrant"/>
 *     &lt;enumeration value="MutuallyDefined"/>
 *     &lt;enumeration value="National"/>
 *     &lt;enumeration value="Regional"/>
 *     &lt;enumeration value="State"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AgencyCodeType")
@XmlEnum
public enum AgencyCodeType {

    @XmlEnumValue("District")
    DISTRICT("District"),
    @XmlEnumValue("Migrant")
    MIGRANT("Migrant"),
    @XmlEnumValue("MutuallyDefined")
    MUTUALLY_DEFINED("MutuallyDefined"),
    @XmlEnumValue("National")
    NATIONAL("National"),
    @XmlEnumValue("Regional")
    REGIONAL("Regional"),
    @XmlEnumValue("State")
    STATE("State");
    private final String value;

    AgencyCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AgencyCodeType fromValue(String v) {
        for (AgencyCodeType c: AgencyCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
