//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CLEnrollmentStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CLEnrollmentStatusCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;minLength value="1"/>
 *     &lt;enumeration value="FullTime"/>
 *     &lt;enumeration value="HalfTime"/>
 *     &lt;enumeration value="LessThanHalfTime"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CLEnrollmentStatusCodeType")
@XmlEnum
public enum CLEnrollmentStatusCodeType {

    @XmlEnumValue("FullTime")
    FULL_TIME("FullTime"),
    @XmlEnumValue("HalfTime")
    HALF_TIME("HalfTime"),
    @XmlEnumValue("LessThanHalfTime")
    LESS_THAN_HALF_TIME("LessThanHalfTime");
    private final String value;

    CLEnrollmentStatusCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CLEnrollmentStatusCodeType fromValue(String v) {
        for (CLEnrollmentStatusCodeType c: CLEnrollmentStatusCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
