//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourseStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CourseStatusCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="InProcess"/>
 *     &lt;enumeration value="NotTaken"/>
 *     &lt;enumeration value="Planned"/>
 *     &lt;enumeration value="Taken"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CourseStatusCodeType")
@XmlEnum
public enum CourseStatusCodeType {

    @XmlEnumValue("InProcess")
    IN_PROCESS("InProcess"),
    @XmlEnumValue("NotTaken")
    NOT_TAKEN("NotTaken"),
    @XmlEnumValue("Planned")
    PLANNED("Planned"),
    @XmlEnumValue("Taken")
    TAKEN("Taken");
    private final String value;

    CourseStatusCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CourseStatusCodeType fromValue(String v) {
        for (CourseStatusCodeType c: CourseStatusCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
