//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourseInstructionMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CourseInstructionMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Lecture"/>
 *     &lt;enumeration value="Laboratory"/>
 *     &lt;enumeration value="Seminar"/>
 *     &lt;enumeration value="IndependentStudy"/>
 *     &lt;enumeration value="Private Study"/>
 *     &lt;enumeration value="PracticeTeaching"/>
 *     &lt;enumeration value="Internship"/>
 *     &lt;enumeration value="Practicum"/>
 *     &lt;enumeration value="ApprenticeshipExternship"/>
 *     &lt;enumeration value="AppliedInstruction"/>
 *     &lt;enumeration value="Residency"/>
 *     &lt;enumeration value="ClinicalRotationInstruction"/>
 *     &lt;enumeration value="SelfPaced"/>
 *     &lt;enumeration value="FieldStudy"/>
 *     &lt;enumeration value="InternetInstruction"/>
 *     &lt;enumeration value="InteractiveVideo"/>
 *     &lt;enumeration value="Videotape"/>
 *     &lt;enumeration value="Television"/>
 *     &lt;enumeration value="OtherDistanceLearning"/>
 *     &lt;enumeration value="Audiotape"/>
 *     &lt;enumeration value="ComputerBasedInstruction"/>
 *     &lt;enumeration value="CompressedVideo"/>
 *     &lt;enumeration value="Correspondence"/>
 *     &lt;enumeration value="CooperativeEducation"/>
 *     &lt;enumeration value="WorkStudy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CourseInstructionMethodType")
@XmlEnum
public enum CourseInstructionMethodType {

    @XmlEnumValue("Lecture")
    LECTURE("Lecture"),
    @XmlEnumValue("Laboratory")
    LABORATORY("Laboratory"),
    @XmlEnumValue("Seminar")
    SEMINAR("Seminar"),
    @XmlEnumValue("IndependentStudy")
    INDEPENDENT_STUDY("IndependentStudy"),
    @XmlEnumValue("Private Study")
    PRIVATE_STUDY("Private Study"),
    @XmlEnumValue("PracticeTeaching")
    PRACTICE_TEACHING("PracticeTeaching"),
    @XmlEnumValue("Internship")
    INTERNSHIP("Internship"),
    @XmlEnumValue("Practicum")
    PRACTICUM("Practicum"),
    @XmlEnumValue("ApprenticeshipExternship")
    APPRENTICESHIP_EXTERNSHIP("ApprenticeshipExternship"),
    @XmlEnumValue("AppliedInstruction")
    APPLIED_INSTRUCTION("AppliedInstruction"),
    @XmlEnumValue("Residency")
    RESIDENCY("Residency"),
    @XmlEnumValue("ClinicalRotationInstruction")
    CLINICAL_ROTATION_INSTRUCTION("ClinicalRotationInstruction"),
    @XmlEnumValue("SelfPaced")
    SELF_PACED("SelfPaced"),
    @XmlEnumValue("FieldStudy")
    FIELD_STUDY("FieldStudy"),
    @XmlEnumValue("InternetInstruction")
    INTERNET_INSTRUCTION("InternetInstruction"),
    @XmlEnumValue("InteractiveVideo")
    INTERACTIVE_VIDEO("InteractiveVideo"),
    @XmlEnumValue("Videotape")
    VIDEOTAPE("Videotape"),
    @XmlEnumValue("Television")
    TELEVISION("Television"),
    @XmlEnumValue("OtherDistanceLearning")
    OTHER_DISTANCE_LEARNING("OtherDistanceLearning"),
    @XmlEnumValue("Audiotape")
    AUDIOTAPE("Audiotape"),
    @XmlEnumValue("ComputerBasedInstruction")
    COMPUTER_BASED_INSTRUCTION("ComputerBasedInstruction"),
    @XmlEnumValue("CompressedVideo")
    COMPRESSED_VIDEO("CompressedVideo"),
    @XmlEnumValue("Correspondence")
    CORRESPONDENCE("Correspondence"),
    @XmlEnumValue("CooperativeEducation")
    COOPERATIVE_EDUCATION("CooperativeEducation"),
    @XmlEnumValue("WorkStudy")
    WORK_STUDY("WorkStudy");
    private final String value;

    CourseInstructionMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CourseInstructionMethodType fromValue(String v) {
        for (CourseInstructionMethodType c: CourseInstructionMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
