//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditDataSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CreditDataSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;minLength value="1"/>
 *     &lt;enumeration value="TransUnion"/>
 *     &lt;enumeration value="Equifax"/>
 *     &lt;enumeration value="Experian"/>
 *     &lt;enumeration value="InnovisDataSolutions"/>
 *     &lt;enumeration value="FairIsaac"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CreditDataSourceType")
@XmlEnum
public enum CreditDataSourceType {

    @XmlEnumValue("TransUnion")
    TRANS_UNION("TransUnion"),
    @XmlEnumValue("Equifax")
    EQUIFAX("Equifax"),
    @XmlEnumValue("Experian")
    EXPERIAN("Experian"),
    @XmlEnumValue("InnovisDataSolutions")
    INNOVIS_DATA_SOLUTIONS("InnovisDataSolutions"),
    @XmlEnumValue("FairIsaac")
    FAIR_ISAAC("FairIsaac");
    private final String value;

    CreditDataSourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CreditDataSourceType fromValue(String v) {
        for (CreditDataSourceType c: CreditDataSourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
