//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element provides a logical grouping of elements related to Debt Data
 * 
 * <p>Java class for DebtDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebtDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalStudentLoanDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalStudentLoanDebtAmountType" minOccurs="0"/>
 *         &lt;element name="StaffordLoanDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}StaffordLoanDebtAmountType" minOccurs="0"/>
 *         &lt;element name="SLSDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}SLSDebtAmountType" minOccurs="0"/>
 *         &lt;element name="HEALDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}HEALDebtAmountType" minOccurs="0"/>
 *         &lt;element name="PerkinsDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}PerkinsDebtAmountType" minOccurs="0"/>
 *         &lt;element name="OtherDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}OtherDebtAmountType" minOccurs="0"/>
 *         &lt;element name="OtherLoansThisPeriodDebtAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}OtherLoansThisPeriodDebtAmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebtDataType", propOrder = {
    "totalStudentLoanDebtAmount",
    "staffordLoanDebtAmount",
    "slsDebtAmount",
    "healDebtAmount",
    "perkinsDebtAmount",
    "otherDebtAmount",
    "otherLoansThisPeriodDebtAmount"
})
public class DebtDataType {

    @XmlElement(name = "TotalStudentLoanDebtAmount")
    protected BigDecimal totalStudentLoanDebtAmount;
    @XmlElement(name = "StaffordLoanDebtAmount")
    protected BigDecimal staffordLoanDebtAmount;
    @XmlElement(name = "SLSDebtAmount")
    protected BigDecimal slsDebtAmount;
    @XmlElement(name = "HEALDebtAmount")
    protected BigDecimal healDebtAmount;
    @XmlElement(name = "PerkinsDebtAmount")
    protected BigDecimal perkinsDebtAmount;
    @XmlElement(name = "OtherDebtAmount")
    protected BigDecimal otherDebtAmount;
    @XmlElement(name = "OtherLoansThisPeriodDebtAmount")
    protected BigDecimal otherLoansThisPeriodDebtAmount;

    /**
     * Gets the value of the totalStudentLoanDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalStudentLoanDebtAmount() {
        return totalStudentLoanDebtAmount;
    }

    /**
     * Sets the value of the totalStudentLoanDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalStudentLoanDebtAmount(BigDecimal value) {
        this.totalStudentLoanDebtAmount = value;
    }

    /**
     * Gets the value of the staffordLoanDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStaffordLoanDebtAmount() {
        return staffordLoanDebtAmount;
    }

    /**
     * Sets the value of the staffordLoanDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStaffordLoanDebtAmount(BigDecimal value) {
        this.staffordLoanDebtAmount = value;
    }

    /**
     * Gets the value of the slsDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSLSDebtAmount() {
        return slsDebtAmount;
    }

    /**
     * Sets the value of the slsDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSLSDebtAmount(BigDecimal value) {
        this.slsDebtAmount = value;
    }

    /**
     * Gets the value of the healDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHEALDebtAmount() {
        return healDebtAmount;
    }

    /**
     * Sets the value of the healDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHEALDebtAmount(BigDecimal value) {
        this.healDebtAmount = value;
    }

    /**
     * Gets the value of the perkinsDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPerkinsDebtAmount() {
        return perkinsDebtAmount;
    }

    /**
     * Sets the value of the perkinsDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPerkinsDebtAmount(BigDecimal value) {
        this.perkinsDebtAmount = value;
    }

    /**
     * Gets the value of the otherDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherDebtAmount() {
        return otherDebtAmount;
    }

    /**
     * Sets the value of the otherDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherDebtAmount(BigDecimal value) {
        this.otherDebtAmount = value;
    }

    /**
     * Gets the value of the otherLoansThisPeriodDebtAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherLoansThisPeriodDebtAmount() {
        return otherLoansThisPeriodDebtAmount;
    }

    /**
     * Sets the value of the otherLoansThisPeriodDebtAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherLoansThisPeriodDebtAmount(BigDecimal value) {
        this.otherLoansThisPeriodDebtAmount = value;
    }

}
