//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EarlyIndicatorCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EarlyIndicatorCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EarlyAction"/>
 *     &lt;enumeration value="EarlyAdmission"/>
 *     &lt;enumeration value="EarlyDecision"/>
 *     &lt;enumeration value="RestrictedEarlyAction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EarlyIndicatorCodeType")
@XmlEnum
public enum EarlyIndicatorCodeType {

    @XmlEnumValue("EarlyAction")
    EARLY_ACTION("EarlyAction"),
    @XmlEnumValue("EarlyAdmission")
    EARLY_ADMISSION("EarlyAdmission"),
    @XmlEnumValue("EarlyDecision")
    EARLY_DECISION("EarlyDecision"),
    @XmlEnumValue("RestrictedEarlyAction")
    RESTRICTED_EARLY_ACTION("RestrictedEarlyAction");
    private final String value;

    EarlyIndicatorCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EarlyIndicatorCodeType fromValue(String v) {
        for (EarlyIndicatorCodeType c: EarlyIndicatorCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
