//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eSignatureCustodianType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eSignatureCustodianType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Lender">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{urn:org:pesc:core:CoreMain:v1.12.0}OrganizationIDGroup"/>
 *                   &lt;element name="NonEDBranchID" type="{urn:org:pesc:core:CoreMain:v1.12.0}NonEDBranchIDType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Guarantor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{urn:org:pesc:core:CoreMain:v1.12.0}OrganizationIDGroup"/>
 *                   &lt;element name="NonEDBranchID" type="{urn:org:pesc:core:CoreMain:v1.12.0}NonEDBranchIDType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eSignatureCustodianType", propOrder = {
    "lender",
    "guarantor"
})
public class ESignatureCustodianType {

    @XmlElement(name = "Lender")
    protected ESignatureCustodianType.Lender lender;
    @XmlElement(name = "Guarantor")
    protected ESignatureCustodianType.Guarantor guarantor;

    /**
     * Gets the value of the lender property.
     * 
     * @return
     *     possible object is
     *     {@link ESignatureCustodianType.Lender }
     *     
     */
    public ESignatureCustodianType.Lender getLender() {
        return lender;
    }

    /**
     * Sets the value of the lender property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESignatureCustodianType.Lender }
     *     
     */
    public void setLender(ESignatureCustodianType.Lender value) {
        this.lender = value;
    }

    /**
     * Gets the value of the guarantor property.
     * 
     * @return
     *     possible object is
     *     {@link ESignatureCustodianType.Guarantor }
     *     
     */
    public ESignatureCustodianType.Guarantor getGuarantor() {
        return guarantor;
    }

    /**
     * Sets the value of the guarantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESignatureCustodianType.Guarantor }
     *     
     */
    public void setGuarantor(ESignatureCustodianType.Guarantor value) {
        this.guarantor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{urn:org:pesc:core:CoreMain:v1.12.0}OrganizationIDGroup"/>
     *         &lt;element name="NonEDBranchID" type="{urn:org:pesc:core:CoreMain:v1.12.0}NonEDBranchIDType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opeid",
        "nchelpid",
        "ipeds",
        "atp",
        "fice",
        "act",
        "ccd",
        "pss",
        "ceebact",
        "csis",
        "usis",
        "esis",
        "psis",
        "duns",
        "mutuallyDefined",
        "nonEDBranchID"
    })
    public static class Guarantor {

        @XmlElement(name = "OPEID")
        protected String opeid;
        @XmlElement(name = "NCHELPID")
        protected String nchelpid;
        @XmlElement(name = "IPEDS")
        protected String ipeds;
        @XmlElement(name = "ATP")
        protected String atp;
        @XmlElement(name = "FICE")
        protected String fice;
        @XmlElement(name = "ACT")
        protected String act;
        @XmlElement(name = "CCD")
        protected String ccd;
        @XmlElement(name = "PSS")
        protected String pss;
        @XmlElement(name = "CEEBACT")
        protected String ceebact;
        @XmlElement(name = "CSIS")
        protected String csis;
        @XmlElement(name = "USIS")
        protected String usis;
        @XmlElement(name = "ESIS")
        protected String esis;
        @XmlElement(name = "PSIS")
        protected String psis;
        @XmlElement(name = "DUNS")
        protected String duns;
        @XmlElement(name = "MutuallyDefined")
        protected String mutuallyDefined;
        @XmlElement(name = "NonEDBranchID")
        protected String nonEDBranchID;

        /**
         * Gets the value of the opeid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOPEID() {
            return opeid;
        }

        /**
         * Sets the value of the opeid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOPEID(String value) {
            this.opeid = value;
        }

        /**
         * Gets the value of the nchelpid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNCHELPID() {
            return nchelpid;
        }

        /**
         * Sets the value of the nchelpid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNCHELPID(String value) {
            this.nchelpid = value;
        }

        /**
         * Gets the value of the ipeds property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIPEDS() {
            return ipeds;
        }

        /**
         * Sets the value of the ipeds property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIPEDS(String value) {
            this.ipeds = value;
        }

        /**
         * Gets the value of the atp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getATP() {
            return atp;
        }

        /**
         * Sets the value of the atp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setATP(String value) {
            this.atp = value;
        }

        /**
         * Gets the value of the fice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFICE() {
            return fice;
        }

        /**
         * Sets the value of the fice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFICE(String value) {
            this.fice = value;
        }

        /**
         * Gets the value of the act property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACT() {
            return act;
        }

        /**
         * Sets the value of the act property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACT(String value) {
            this.act = value;
        }

        /**
         * Gets the value of the ccd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCCD() {
            return ccd;
        }

        /**
         * Sets the value of the ccd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCCD(String value) {
            this.ccd = value;
        }

        /**
         * Gets the value of the pss property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSS() {
            return pss;
        }

        /**
         * Sets the value of the pss property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSS(String value) {
            this.pss = value;
        }

        /**
         * Gets the value of the ceebact property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCEEBACT() {
            return ceebact;
        }

        /**
         * Sets the value of the ceebact property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCEEBACT(String value) {
            this.ceebact = value;
        }

        /**
         * Gets the value of the csis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCSIS() {
            return csis;
        }

        /**
         * Sets the value of the csis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCSIS(String value) {
            this.csis = value;
        }

        /**
         * Gets the value of the usis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSIS() {
            return usis;
        }

        /**
         * Sets the value of the usis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSIS(String value) {
            this.usis = value;
        }

        /**
         * Gets the value of the esis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getESIS() {
            return esis;
        }

        /**
         * Sets the value of the esis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setESIS(String value) {
            this.esis = value;
        }

        /**
         * Gets the value of the psis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSIS() {
            return psis;
        }

        /**
         * Sets the value of the psis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSIS(String value) {
            this.psis = value;
        }

        /**
         * Gets the value of the duns property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDUNS() {
            return duns;
        }

        /**
         * Sets the value of the duns property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDUNS(String value) {
            this.duns = value;
        }

        /**
         * Gets the value of the mutuallyDefined property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMutuallyDefined() {
            return mutuallyDefined;
        }

        /**
         * Sets the value of the mutuallyDefined property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMutuallyDefined(String value) {
            this.mutuallyDefined = value;
        }

        /**
         * Gets the value of the nonEDBranchID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNonEDBranchID() {
            return nonEDBranchID;
        }

        /**
         * Sets the value of the nonEDBranchID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNonEDBranchID(String value) {
            this.nonEDBranchID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{urn:org:pesc:core:CoreMain:v1.12.0}OrganizationIDGroup"/>
     *         &lt;element name="NonEDBranchID" type="{urn:org:pesc:core:CoreMain:v1.12.0}NonEDBranchIDType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opeid",
        "nchelpid",
        "ipeds",
        "atp",
        "fice",
        "act",
        "ccd",
        "pss",
        "ceebact",
        "csis",
        "usis",
        "esis",
        "psis",
        "duns",
        "mutuallyDefined",
        "nonEDBranchID"
    })
    public static class Lender {

        @XmlElement(name = "OPEID")
        protected String opeid;
        @XmlElement(name = "NCHELPID")
        protected String nchelpid;
        @XmlElement(name = "IPEDS")
        protected String ipeds;
        @XmlElement(name = "ATP")
        protected String atp;
        @XmlElement(name = "FICE")
        protected String fice;
        @XmlElement(name = "ACT")
        protected String act;
        @XmlElement(name = "CCD")
        protected String ccd;
        @XmlElement(name = "PSS")
        protected String pss;
        @XmlElement(name = "CEEBACT")
        protected String ceebact;
        @XmlElement(name = "CSIS")
        protected String csis;
        @XmlElement(name = "USIS")
        protected String usis;
        @XmlElement(name = "ESIS")
        protected String esis;
        @XmlElement(name = "PSIS")
        protected String psis;
        @XmlElement(name = "DUNS")
        protected String duns;
        @XmlElement(name = "MutuallyDefined")
        protected String mutuallyDefined;
        @XmlElement(name = "NonEDBranchID")
        protected String nonEDBranchID;

        /**
         * Gets the value of the opeid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOPEID() {
            return opeid;
        }

        /**
         * Sets the value of the opeid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOPEID(String value) {
            this.opeid = value;
        }

        /**
         * Gets the value of the nchelpid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNCHELPID() {
            return nchelpid;
        }

        /**
         * Sets the value of the nchelpid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNCHELPID(String value) {
            this.nchelpid = value;
        }

        /**
         * Gets the value of the ipeds property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIPEDS() {
            return ipeds;
        }

        /**
         * Sets the value of the ipeds property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIPEDS(String value) {
            this.ipeds = value;
        }

        /**
         * Gets the value of the atp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getATP() {
            return atp;
        }

        /**
         * Sets the value of the atp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setATP(String value) {
            this.atp = value;
        }

        /**
         * Gets the value of the fice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFICE() {
            return fice;
        }

        /**
         * Sets the value of the fice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFICE(String value) {
            this.fice = value;
        }

        /**
         * Gets the value of the act property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACT() {
            return act;
        }

        /**
         * Sets the value of the act property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACT(String value) {
            this.act = value;
        }

        /**
         * Gets the value of the ccd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCCD() {
            return ccd;
        }

        /**
         * Sets the value of the ccd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCCD(String value) {
            this.ccd = value;
        }

        /**
         * Gets the value of the pss property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSS() {
            return pss;
        }

        /**
         * Sets the value of the pss property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSS(String value) {
            this.pss = value;
        }

        /**
         * Gets the value of the ceebact property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCEEBACT() {
            return ceebact;
        }

        /**
         * Sets the value of the ceebact property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCEEBACT(String value) {
            this.ceebact = value;
        }

        /**
         * Gets the value of the csis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCSIS() {
            return csis;
        }

        /**
         * Sets the value of the csis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCSIS(String value) {
            this.csis = value;
        }

        /**
         * Gets the value of the usis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSIS() {
            return usis;
        }

        /**
         * Sets the value of the usis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSIS(String value) {
            this.usis = value;
        }

        /**
         * Gets the value of the esis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getESIS() {
            return esis;
        }

        /**
         * Sets the value of the esis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setESIS(String value) {
            this.esis = value;
        }

        /**
         * Gets the value of the psis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSIS() {
            return psis;
        }

        /**
         * Sets the value of the psis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSIS(String value) {
            this.psis = value;
        }

        /**
         * Gets the value of the duns property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDUNS() {
            return duns;
        }

        /**
         * Sets the value of the duns property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDUNS(String value) {
            this.duns = value;
        }

        /**
         * Gets the value of the mutuallyDefined property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMutuallyDefined() {
            return mutuallyDefined;
        }

        /**
         * Sets the value of the mutuallyDefined property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMutuallyDefined(String value) {
            this.mutuallyDefined = value;
        }

        /**
         * Gets the value of the nonEDBranchID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNonEDBranchID() {
            return nonEDBranchID;
        }

        /**
         * Sets the value of the nonEDBranchID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNonEDBranchID(String value) {
            this.nonEDBranchID = value;
        }

    }

}
