//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The cultural, tribal or national background of a person
 * 
 * <p>Java class for EthnicityRaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EthnicityRaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EthnicityCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}EthnicityCodeType" minOccurs="0"/>
 *         &lt;element name="RaceCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}RaceCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LocalEthnicityRaceCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}LocalEthnicityRaceCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EthnicityRaceType", propOrder = {
    "ethnicityCode",
    "raceCode",
    "localEthnicityRaceCode",
    "noteMessage"
})
public class EthnicityRaceType {

    @XmlElement(name = "EthnicityCode")
    protected EthnicityCodeType ethnicityCode;
    @XmlElement(name = "RaceCode")
    protected List<RaceCodeType> raceCode;
    @XmlElement(name = "LocalEthnicityRaceCode")
    protected List<String> localEthnicityRaceCode;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the ethnicityCode property.
     * 
     * @return
     *     possible object is
     *     {@link EthnicityCodeType }
     *     
     */
    public EthnicityCodeType getEthnicityCode() {
        return ethnicityCode;
    }

    /**
     * Sets the value of the ethnicityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EthnicityCodeType }
     *     
     */
    public void setEthnicityCode(EthnicityCodeType value) {
        this.ethnicityCode = value;
    }

    /**
     * Gets the value of the raceCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the raceCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRaceCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RaceCodeType }
     * 
     * 
     */
    public List<RaceCodeType> getRaceCode() {
        if (raceCode == null) {
            raceCode = new ArrayList<RaceCodeType>();
        }
        return this.raceCode;
    }

    /**
     * Gets the value of the localEthnicityRaceCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localEthnicityRaceCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalEthnicityRaceCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLocalEthnicityRaceCode() {
        if (localEthnicityRaceCode == null) {
            localEthnicityRaceCode = new ArrayList<String>();
        }
        return this.localEthnicityRaceCode;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
