//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeeWaiverBasisCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FeeWaiverBasisCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AmeriCorps"/>
 *     &lt;enumeration value="Employee"/>
 *     &lt;enumeration value="EmployeeDependent"/>
 *     &lt;enumeration value="GoverningBoard"/>
 *     &lt;enumeration value="LowIncome"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="PeaceCorps"/>
 *     &lt;enumeration value="PreviouslyPaid"/>
 *     &lt;enumeration value="School"/>
 *     &lt;enumeration value="SeniorCitizen"/>
 *     &lt;enumeration value="TestAgency"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FeeWaiverBasisCodeType")
@XmlEnum
public enum FeeWaiverBasisCodeType {

    @XmlEnumValue("AmeriCorps")
    AMERI_CORPS("AmeriCorps"),
    @XmlEnumValue("Employee")
    EMPLOYEE("Employee"),
    @XmlEnumValue("EmployeeDependent")
    EMPLOYEE_DEPENDENT("EmployeeDependent"),
    @XmlEnumValue("GoverningBoard")
    GOVERNING_BOARD("GoverningBoard"),
    @XmlEnumValue("LowIncome")
    LOW_INCOME("LowIncome"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("PeaceCorps")
    PEACE_CORPS("PeaceCorps"),
    @XmlEnumValue("PreviouslyPaid")
    PREVIOUSLY_PAID("PreviouslyPaid"),
    @XmlEnumValue("School")
    SCHOOL("School"),
    @XmlEnumValue("SeniorCitizen")
    SENIOR_CITIZEN("SeniorCitizen"),
    @XmlEnumValue("TestAgency")
    TEST_AGENCY("TestAgency");
    private final String value;

    FeeWaiverBasisCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FeeWaiverBasisCodeType fromValue(String v) {
        for (FeeWaiverBasisCodeType c: FeeWaiverBasisCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
