//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenderChangeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GenderChangeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ChangeFemale"/>
 *     &lt;enumeration value="ChangeMale"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GenderChangeCodeType")
@XmlEnum
public enum GenderChangeCodeType {

    @XmlEnumValue("ChangeFemale")
    CHANGE_FEMALE("ChangeFemale"),
    @XmlEnumValue("ChangeMale")
    CHANGE_MALE("ChangeMale");
    private final String value;

    GenderChangeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GenderChangeCodeType fromValue(String v) {
        for (GenderChangeCodeType c: GenderChangeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
