//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HighSchoolCreditSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HighSchoolCreditSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HighSchoolSubjectArea" type="{urn:org:pesc:core:CoreMain:v1.12.0}HighSchoolSubjectAreaType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HighSchoolCreditSummaryType", propOrder = {
    "highSchoolSubjectArea"
})
public class HighSchoolCreditSummaryType {

    @XmlElement(name = "HighSchoolSubjectArea")
    protected List<HighSchoolSubjectAreaType> highSchoolSubjectArea;

    /**
     * Gets the value of the highSchoolSubjectArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the highSchoolSubjectArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHighSchoolSubjectArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HighSchoolSubjectAreaType }
     * 
     * 
     */
    public List<HighSchoolSubjectAreaType> getHighSchoolSubjectArea() {
        if (highSchoolSubjectArea == null) {
            highSchoolSubjectArea = new ArrayList<HighSchoolSubjectAreaType>();
        }
        return this.highSchoolSubjectArea;
    }

}
