//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element provides a logical grouping of elements related to Income Data
 * 
 * <p>Java class for IncomeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncomeDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrossAnnualSalary" type="{urn:org:pesc:core:CoreMain:v1.12.0}GrossAnnualSalaryType" minOccurs="0"/>
 *         &lt;element name="OtherIncome" type="{urn:org:pesc:core:CoreMain:v1.12.0}OtherIncomeType" minOccurs="0"/>
 *         &lt;element name="OtherIncomeSource" type="{urn:org:pesc:core:CoreMain:v1.12.0}OtherIncomeSourceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncomeDataType", propOrder = {
    "grossAnnualSalary",
    "otherIncome",
    "otherIncomeSource"
})
public class IncomeDataType {

    @XmlElement(name = "GrossAnnualSalary")
    protected BigDecimal grossAnnualSalary;
    @XmlElement(name = "OtherIncome")
    protected BigDecimal otherIncome;
    @XmlElement(name = "OtherIncomeSource")
    protected String otherIncomeSource;

    /**
     * Gets the value of the grossAnnualSalary property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossAnnualSalary() {
        return grossAnnualSalary;
    }

    /**
     * Sets the value of the grossAnnualSalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossAnnualSalary(BigDecimal value) {
        this.grossAnnualSalary = value;
    }

    /**
     * Gets the value of the otherIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherIncome() {
        return otherIncome;
    }

    /**
     * Sets the value of the otherIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherIncome(BigDecimal value) {
        this.otherIncome = value;
    }

    /**
     * Gets the value of the otherIncomeSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherIncomeSource() {
        return otherIncomeSource;
    }

    /**
     * Sets the value of the otherIncomeSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherIncomeSource(String value) {
        this.otherIncomeSource = value;
    }

}
