//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoanAwardResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanAwardResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:org:pesc:core:CoreMain:v1.12.0}ResponseType">
 *       &lt;sequence>
 *         &lt;element name="EMPNIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MPNID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="23"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MPNStatusCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="A"/>
 *               &lt;enumeration value="R"/>
 *               &lt;enumeration value="X"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MPNLinkIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanAwardResponseType", propOrder = {
    "empnIndicator",
    "mpnid",
    "mpnStatusCode",
    "mpnLinkIndicator"
})
@XmlSeeAlso({
    DLAwardResponseType.class
})
public class LoanAwardResponseType
    extends ResponseType
{

    @XmlElement(name = "EMPNIndicator")
    protected Boolean empnIndicator;
    @XmlElement(name = "MPNID")
    protected String mpnid;
    @XmlElement(name = "MPNStatusCode")
    protected String mpnStatusCode;
    @XmlElement(name = "MPNLinkIndicator")
    protected Boolean mpnLinkIndicator;

    /**
     * Gets the value of the empnIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEMPNIndicator() {
        return empnIndicator;
    }

    /**
     * Sets the value of the empnIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEMPNIndicator(Boolean value) {
        this.empnIndicator = value;
    }

    /**
     * Gets the value of the mpnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMPNID() {
        return mpnid;
    }

    /**
     * Sets the value of the mpnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMPNID(String value) {
        this.mpnid = value;
    }

    /**
     * Gets the value of the mpnStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMPNStatusCode() {
        return mpnStatusCode;
    }

    /**
     * Sets the value of the mpnStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMPNStatusCode(String value) {
        this.mpnStatusCode = value;
    }

    /**
     * Gets the value of the mpnLinkIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMPNLinkIndicator() {
        return mpnLinkIndicator;
    }

    /**
     * Sets the value of the mpnLinkIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMPNLinkIndicator(Boolean value) {
        this.mpnLinkIndicator = value;
    }

}
