//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LoanAwardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanAwardType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:org:pesc:core:CoreMain:v1.12.0}FinancialAwardType">
 *       &lt;sequence>
 *         &lt;element name="DependencyStatusCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="I"/>
 *               &lt;enumeration value="D"/>
 *               &lt;enumeration value="Dependent"/>
 *               &lt;enumeration value="Independent"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DefaultOverpayCode" type="{urn:org:pesc:core:CoreMain:v1.12.0}DefaultOverpayCodeType" minOccurs="0"/>
 *         &lt;element name="FinancialAwardNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FinancialAwardID" type="{urn:org:pesc:core:CoreMain:v1.12.0}FinancialAwardIDType" minOccurs="0"/>
 *         &lt;element name="FinancialAwardCreateDate" type="{urn:org:pesc:core:CoreMain:v1.12.0}FinancialAwardCreateDateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanAwardType", propOrder = {
    "dependencyStatusCode",
    "defaultOverpayCode",
    "financialAwardNumber",
    "financialAwardID",
    "financialAwardCreateDate"
})
@XmlSeeAlso({
    PLUSAwardType.class,
    StaffordAwardType.class
})
public class LoanAwardType
    extends FinancialAwardType
{

    @XmlElementRef(name = "DependencyStatusCode", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dependencyStatusCode;
    @XmlElement(name = "DefaultOverpayCode")
    protected DefaultOverpayCodeType defaultOverpayCode;
    @XmlElement(name = "FinancialAwardNumber")
    protected Integer financialAwardNumber;
    @XmlElement(name = "FinancialAwardID")
    protected String financialAwardID;
    @XmlElementRef(name = "FinancialAwardCreateDate", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> financialAwardCreateDate;

    /**
     * Gets the value of the dependencyStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDependencyStatusCode() {
        return dependencyStatusCode;
    }

    /**
     * Sets the value of the dependencyStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDependencyStatusCode(JAXBElement<String> value) {
        this.dependencyStatusCode = value;
    }

    /**
     * Gets the value of the defaultOverpayCode property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultOverpayCodeType }
     *     
     */
    public DefaultOverpayCodeType getDefaultOverpayCode() {
        return defaultOverpayCode;
    }

    /**
     * Sets the value of the defaultOverpayCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultOverpayCodeType }
     *     
     */
    public void setDefaultOverpayCode(DefaultOverpayCodeType value) {
        this.defaultOverpayCode = value;
    }

    /**
     * Gets the value of the financialAwardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFinancialAwardNumber() {
        return financialAwardNumber;
    }

    /**
     * Sets the value of the financialAwardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFinancialAwardNumber(Integer value) {
        this.financialAwardNumber = value;
    }

    /**
     * Gets the value of the financialAwardID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialAwardID() {
        return financialAwardID;
    }

    /**
     * Sets the value of the financialAwardID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialAwardID(String value) {
        this.financialAwardID = value;
    }

    /**
     * Gets the value of the financialAwardCreateDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getFinancialAwardCreateDate() {
        return financialAwardCreateDate;
    }

    /**
     * Sets the value of the financialAwardCreateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setFinancialAwardCreateDate(JAXBElement<XMLGregorianCalendar> value) {
        this.financialAwardCreateDate = value;
    }

}
