//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * NOT USED (must check)
 * 
 * <p>Java class for NCHELPIDGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NCHELPIDGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NCHELPID" type="{urn:org:pesc:core:CoreMain:v1.12.0}NCHELPIDType"/>
 *         &lt;element name="NonEDBranchID" type="{urn:org:pesc:core:CoreMain:v1.12.0}NonEDBranchIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NCHELPIDGroupType", propOrder = {
    "nchelpid",
    "nonEDBranchID"
})
public class NCHELPIDGroupType {

    @XmlElement(name = "NCHELPID", required = true)
    protected String nchelpid;
    @XmlElement(name = "NonEDBranchID")
    protected String nonEDBranchID;

    /**
     * Gets the value of the nchelpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCHELPID() {
        return nchelpid;
    }

    /**
     * Sets the value of the nchelpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCHELPID(String value) {
        this.nchelpid = value;
    }

    /**
     * Gets the value of the nonEDBranchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonEDBranchID() {
        return nonEDBranchID;
    }

    /**
     * Sets the value of the nonEDBranchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonEDBranchID(String value) {
        this.nonEDBranchID = value;
    }

}
