//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonImmigrantVisaStatusChangeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NonImmigrantVisaStatusChangeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NoChange"/>
 *     &lt;enumeration value="StatusChange"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NonImmigrantVisaStatusChangeCodeType")
@XmlEnum
public enum NonImmigrantVisaStatusChangeCodeType {

    @XmlEnumValue("NoChange")
    NO_CHANGE("NoChange"),
    @XmlEnumValue("StatusChange")
    STATUS_CHANGE("StatusChange");
    private final String value;

    NonImmigrantVisaStatusChangeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NonImmigrantVisaStatusChangeCodeType fromValue(String v) {
        for (NonImmigrantVisaStatusChangeCodeType c: NonImmigrantVisaStatusChangeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
