//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NormPopulationCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NormPopulationCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Institution"/>
 *     &lt;enumeration value="City"/>
 *     &lt;enumeration value="County"/>
 *     &lt;enumeration value="State"/>
 *     &lt;enumeration value="Region"/>
 *     &lt;enumeration value="National"/>
 *     &lt;enumeration value="International"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NormPopulationCodeType")
@XmlEnum
public enum NormPopulationCodeType {

    @XmlEnumValue("Institution")
    INSTITUTION("Institution"),
    @XmlEnumValue("City")
    CITY("City"),
    @XmlEnumValue("County")
    COUNTY("County"),
    @XmlEnumValue("State")
    STATE("State"),
    @XmlEnumValue("Region")
    REGION("Region"),
    @XmlEnumValue("National")
    NATIONAL("National"),
    @XmlEnumValue("International")
    INTERNATIONAL("International"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    NormPopulationCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NormPopulationCodeType fromValue(String v) {
        for (NormPopulationCodeType c: NormPopulationCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
