//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PellAwardResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PellAwardResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:org:pesc:core:CoreMain:v1.12.0}ResponseType">
 *       &lt;sequence>
 *         &lt;element name="YTDDisbursementAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}SmallCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalEligibilityUsed" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="999.999"/>
 *               &lt;totalDigits value="6"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ScheduledPellGrant" type="{urn:org:pesc:core:CoreMain:v1.12.0}SmallCurrencyType" minOccurs="0"/>
 *         &lt;element name="NegativePendingAmount" type="{urn:org:pesc:core:CoreMain:v1.12.0}SmallCurrencyType" minOccurs="0"/>
 *         &lt;element name="FSACode" maxOccurs="3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SA"/>
 *               &lt;enumeration value="CE"/>
 *               &lt;enumeration value="PO"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PellAwardResponseType", propOrder = {
    "ytdDisbursementAmount",
    "totalEligibilityUsed",
    "scheduledPellGrant",
    "negativePendingAmount",
    "fsaCode"
})
public class PellAwardResponseType
    extends ResponseType
{

    @XmlElement(name = "YTDDisbursementAmount")
    protected BigDecimal ytdDisbursementAmount;
    @XmlElement(name = "TotalEligibilityUsed")
    protected BigDecimal totalEligibilityUsed;
    @XmlElementRef(name = "ScheduledPellGrant", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> scheduledPellGrant;
    @XmlElement(name = "NegativePendingAmount")
    protected BigDecimal negativePendingAmount;
    @XmlElement(name = "FSACode")
    protected List<String> fsaCode;

    /**
     * Gets the value of the ytdDisbursementAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYTDDisbursementAmount() {
        return ytdDisbursementAmount;
    }

    /**
     * Sets the value of the ytdDisbursementAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYTDDisbursementAmount(BigDecimal value) {
        this.ytdDisbursementAmount = value;
    }

    /**
     * Gets the value of the totalEligibilityUsed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalEligibilityUsed() {
        return totalEligibilityUsed;
    }

    /**
     * Sets the value of the totalEligibilityUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalEligibilityUsed(BigDecimal value) {
        this.totalEligibilityUsed = value;
    }

    /**
     * Gets the value of the scheduledPellGrant property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getScheduledPellGrant() {
        return scheduledPellGrant;
    }

    /**
     * Sets the value of the scheduledPellGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setScheduledPellGrant(JAXBElement<BigDecimal> value) {
        this.scheduledPellGrant = value;
    }

    /**
     * Gets the value of the negativePendingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNegativePendingAmount() {
        return negativePendingAmount;
    }

    /**
     * Sets the value of the negativePendingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNegativePendingAmount(BigDecimal value) {
        this.negativePendingAmount = value;
    }

    /**
     * Gets the value of the fsaCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fsaCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFSACode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFSACode() {
        if (fsaCode == null) {
            fsaCode = new ArrayList<String>();
        }
        return this.fsaCode;
    }

}
