//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PellDisbursementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PellDisbursementType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:org:pesc:core:CoreMain:v1.12.0}CODDisbursementType">
 *       &lt;sequence>
 *         &lt;element name="PaymentPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PellDisbursementType", propOrder = {
    "paymentPeriodStartDate"
})
@XmlSeeAlso({
    org.pesc.core.coremain.v1_12.PellType.Disbursement.class
})
public class PellDisbursementType
    extends CODDisbursementType
{

    @XmlElementRef(name = "PaymentPeriodStartDate", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> paymentPeriodStartDate;

    /**
     * Gets the value of the paymentPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getPaymentPeriodStartDate() {
        return paymentPeriodStartDate;
    }

    /**
     * Sets the value of the paymentPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setPaymentPeriodStartDate(JAXBElement<XMLGregorianCalendar> value) {
        this.paymentPeriodStartDate = value;
    }

}
