//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessingTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessingTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;minLength value="1"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="CP"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="GO"/>
 *     &lt;enumeration value="GP"/>
 *     &lt;enumeration value="PG"/>
 *     &lt;enumeration value="PO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProcessingTypeCodeType")
@XmlEnum
public enum ProcessingTypeCodeType {

    CO,
    CP,
    CR,
    GO,
    GP,
    PG,
    PO;

    public String value() {
        return name();
    }

    public static ProcessingTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
