//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProgramSecondarySchoolCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProgramSecondarySchoolCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CareerPrep"/>
 *     &lt;enumeration value="CollegePrep"/>
 *     &lt;enumeration value="CollegePrepOrCollegeTechPrep"/>
 *     &lt;enumeration value="CollegeTechPrep"/>
 *     &lt;enumeration value="General"/>
 *     &lt;enumeration value="Occupational"/>
 *     &lt;enumeration value="Vocational"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProgramSecondarySchoolCodeType")
@XmlEnum
public enum ProgramSecondarySchoolCodeType {

    @XmlEnumValue("CareerPrep")
    CAREER_PREP("CareerPrep"),
    @XmlEnumValue("CollegePrep")
    COLLEGE_PREP("CollegePrep"),
    @XmlEnumValue("CollegePrepOrCollegeTechPrep")
    COLLEGE_PREP_OR_COLLEGE_TECH_PREP("CollegePrepOrCollegeTechPrep"),
    @XmlEnumValue("CollegeTechPrep")
    COLLEGE_TECH_PREP("CollegeTechPrep"),
    @XmlEnumValue("General")
    GENERAL("General"),
    @XmlEnumValue("Occupational")
    OCCUPATIONAL("Occupational"),
    @XmlEnumValue("Vocational")
    VOCATIONAL("Vocational");
    private final String value;

    ProgramSecondarySchoolCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProgramSecondarySchoolCodeType fromValue(String v) {
        for (ProgramSecondarySchoolCodeType c: ProgramSecondarySchoolCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
