//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResidencyStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResidencyStatusCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="InCity"/>
 *     &lt;enumeration value="InCounty"/>
 *     &lt;enumeration value="InDistrict"/>
 *     &lt;enumeration value="InState"/>
 *     &lt;enumeration value="NonResident"/>
 *     &lt;enumeration value="NotReported"/>
 *     &lt;enumeration value="OtherResident"/>
 *     &lt;enumeration value="Resident"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResidencyStatusCodeType")
@XmlEnum
public enum ResidencyStatusCodeType {

    @XmlEnumValue("InCity")
    IN_CITY("InCity"),
    @XmlEnumValue("InCounty")
    IN_COUNTY("InCounty"),
    @XmlEnumValue("InDistrict")
    IN_DISTRICT("InDistrict"),
    @XmlEnumValue("InState")
    IN_STATE("InState"),
    @XmlEnumValue("NonResident")
    NON_RESIDENT("NonResident"),
    @XmlEnumValue("NotReported")
    NOT_REPORTED("NotReported"),
    @XmlEnumValue("OtherResident")
    OTHER_RESIDENT("OtherResident"),
    @XmlEnumValue("Resident")
    RESIDENT("Resident");
    private final String value;

    ResidencyStatusCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResidencyStatusCodeType fromValue(String v) {
        for (ResidencyStatusCodeType c: ResidencyStatusCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
