//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ResponseFinancialSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseFinancialSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FinancialAwardType" type="{urn:org:pesc:core:CoreMain:v1.12.0}FinancialAwardTypeType"/>
 *         &lt;element name="FinancialAwardYear" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;element name="TotalCount" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType"/>
 *         &lt;element name="TotalCountAccepted" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType" minOccurs="0"/>
 *         &lt;element name="TotalCountRejected" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType" minOccurs="0"/>
 *         &lt;element name="TotalCountCorrected" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType" minOccurs="0"/>
 *         &lt;element name="TotalCountDuplicate" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType" minOccurs="0"/>
 *         &lt;element name="TotalCountVerificationSelected" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType" minOccurs="0"/>
 *         &lt;element name="TotalCountSSAdministration" type="{urn:org:pesc:core:CoreMain:v1.12.0}TotalCountType" minOccurs="0"/>
 *         &lt;element name="TotalReportedAward" type="{urn:org:pesc:core:CoreMain:v1.12.0}LargeCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalReportedDisbursement" type="{urn:org:pesc:core:CoreMain:v1.12.0}LargeCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalFinancialAwardAccepted" type="{urn:org:pesc:core:CoreMain:v1.12.0}LargeCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalFinancialDisbursementAccepted" type="{urn:org:pesc:core:CoreMain:v1.12.0}SignedLargeCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalFundedDisbursementAccepted" type="{urn:org:pesc:core:CoreMain:v1.12.0}SignedLargeCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalNonFundedDisbursementAccepted" type="{urn:org:pesc:core:CoreMain:v1.12.0}SignedLargeCurrencyType" minOccurs="0"/>
 *         &lt;element name="TotalFinancialAwardCorrected" type="{urn:org:pesc:core:CoreMain:v1.12.0}LargeCurrencyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseFinancialSummaryType", propOrder = {
    "financialAwardType",
    "financialAwardYear",
    "totalCount",
    "totalCountAccepted",
    "totalCountRejected",
    "totalCountCorrected",
    "totalCountDuplicate",
    "totalCountVerificationSelected",
    "totalCountSSAdministration",
    "totalReportedAward",
    "totalReportedDisbursement",
    "totalFinancialAwardAccepted",
    "totalFinancialDisbursementAccepted",
    "totalFundedDisbursementAccepted",
    "totalNonFundedDisbursementAccepted",
    "totalFinancialAwardCorrected"
})
@XmlSeeAlso({
    org.pesc.core.coremain.v1_12.ReportingSchoolResponseType.ResponseFinancialSummary.class
})
public class ResponseFinancialSummaryType {

    @XmlElement(name = "FinancialAwardType", required = true)
    protected FinancialAwardTypeType financialAwardType;
    @XmlElement(name = "FinancialAwardYear", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar financialAwardYear;
    @XmlElement(name = "TotalCount")
    protected int totalCount;
    @XmlElement(name = "TotalCountAccepted")
    protected Integer totalCountAccepted;
    @XmlElement(name = "TotalCountRejected")
    protected Integer totalCountRejected;
    @XmlElement(name = "TotalCountCorrected")
    protected Integer totalCountCorrected;
    @XmlElement(name = "TotalCountDuplicate")
    protected Integer totalCountDuplicate;
    @XmlElement(name = "TotalCountVerificationSelected")
    protected Integer totalCountVerificationSelected;
    @XmlElement(name = "TotalCountSSAdministration")
    protected Integer totalCountSSAdministration;
    @XmlElement(name = "TotalReportedAward")
    protected BigDecimal totalReportedAward;
    @XmlElement(name = "TotalReportedDisbursement")
    protected BigDecimal totalReportedDisbursement;
    @XmlElement(name = "TotalFinancialAwardAccepted")
    protected BigDecimal totalFinancialAwardAccepted;
    @XmlElement(name = "TotalFinancialDisbursementAccepted")
    protected BigDecimal totalFinancialDisbursementAccepted;
    @XmlElement(name = "TotalFundedDisbursementAccepted")
    protected BigDecimal totalFundedDisbursementAccepted;
    @XmlElement(name = "TotalNonFundedDisbursementAccepted")
    protected BigDecimal totalNonFundedDisbursementAccepted;
    @XmlElement(name = "TotalFinancialAwardCorrected")
    protected BigDecimal totalFinancialAwardCorrected;

    /**
     * Gets the value of the financialAwardType property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialAwardTypeType }
     *     
     */
    public FinancialAwardTypeType getFinancialAwardType() {
        return financialAwardType;
    }

    /**
     * Sets the value of the financialAwardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialAwardTypeType }
     *     
     */
    public void setFinancialAwardType(FinancialAwardTypeType value) {
        this.financialAwardType = value;
    }

    /**
     * Gets the value of the financialAwardYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinancialAwardYear() {
        return financialAwardYear;
    }

    /**
     * Sets the value of the financialAwardYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinancialAwardYear(XMLGregorianCalendar value) {
        this.financialAwardYear = value;
    }

    /**
     * Gets the value of the totalCount property.
     * 
     */
    public int getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the value of the totalCount property.
     * 
     */
    public void setTotalCount(int value) {
        this.totalCount = value;
    }

    /**
     * Gets the value of the totalCountAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCountAccepted() {
        return totalCountAccepted;
    }

    /**
     * Sets the value of the totalCountAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCountAccepted(Integer value) {
        this.totalCountAccepted = value;
    }

    /**
     * Gets the value of the totalCountRejected property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCountRejected() {
        return totalCountRejected;
    }

    /**
     * Sets the value of the totalCountRejected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCountRejected(Integer value) {
        this.totalCountRejected = value;
    }

    /**
     * Gets the value of the totalCountCorrected property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCountCorrected() {
        return totalCountCorrected;
    }

    /**
     * Sets the value of the totalCountCorrected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCountCorrected(Integer value) {
        this.totalCountCorrected = value;
    }

    /**
     * Gets the value of the totalCountDuplicate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCountDuplicate() {
        return totalCountDuplicate;
    }

    /**
     * Sets the value of the totalCountDuplicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCountDuplicate(Integer value) {
        this.totalCountDuplicate = value;
    }

    /**
     * Gets the value of the totalCountVerificationSelected property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCountVerificationSelected() {
        return totalCountVerificationSelected;
    }

    /**
     * Sets the value of the totalCountVerificationSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCountVerificationSelected(Integer value) {
        this.totalCountVerificationSelected = value;
    }

    /**
     * Gets the value of the totalCountSSAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCountSSAdministration() {
        return totalCountSSAdministration;
    }

    /**
     * Sets the value of the totalCountSSAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCountSSAdministration(Integer value) {
        this.totalCountSSAdministration = value;
    }

    /**
     * Gets the value of the totalReportedAward property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalReportedAward() {
        return totalReportedAward;
    }

    /**
     * Sets the value of the totalReportedAward property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalReportedAward(BigDecimal value) {
        this.totalReportedAward = value;
    }

    /**
     * Gets the value of the totalReportedDisbursement property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalReportedDisbursement() {
        return totalReportedDisbursement;
    }

    /**
     * Sets the value of the totalReportedDisbursement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalReportedDisbursement(BigDecimal value) {
        this.totalReportedDisbursement = value;
    }

    /**
     * Gets the value of the totalFinancialAwardAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFinancialAwardAccepted() {
        return totalFinancialAwardAccepted;
    }

    /**
     * Sets the value of the totalFinancialAwardAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalFinancialAwardAccepted(BigDecimal value) {
        this.totalFinancialAwardAccepted = value;
    }

    /**
     * Gets the value of the totalFinancialDisbursementAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFinancialDisbursementAccepted() {
        return totalFinancialDisbursementAccepted;
    }

    /**
     * Sets the value of the totalFinancialDisbursementAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalFinancialDisbursementAccepted(BigDecimal value) {
        this.totalFinancialDisbursementAccepted = value;
    }

    /**
     * Gets the value of the totalFundedDisbursementAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFundedDisbursementAccepted() {
        return totalFundedDisbursementAccepted;
    }

    /**
     * Sets the value of the totalFundedDisbursementAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalFundedDisbursementAccepted(BigDecimal value) {
        this.totalFundedDisbursementAccepted = value;
    }

    /**
     * Gets the value of the totalNonFundedDisbursementAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNonFundedDisbursementAccepted() {
        return totalNonFundedDisbursementAccepted;
    }

    /**
     * Sets the value of the totalNonFundedDisbursementAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNonFundedDisbursementAccepted(BigDecimal value) {
        this.totalNonFundedDisbursementAccepted = value;
    }

    /**
     * Gets the value of the totalFinancialAwardCorrected property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFinancialAwardCorrected() {
        return totalFinancialAwardCorrected;
    }

    /**
     * Sets the value of the totalFinancialAwardCorrected property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalFinancialAwardCorrected(BigDecimal value) {
        this.totalFinancialAwardCorrected = value;
    }

}
