//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScoreExclusionReasonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScoreExclusionReasonCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Absent"/>
 *     &lt;enumeration value="AdministrativeCancellation"/>
 *     &lt;enumeration value="AdministrativeDiscretion"/>
 *     &lt;enumeration value="ExamineeCancellation"/>
 *     &lt;enumeration value="ExtraordinaryCircumstances"/>
 *     &lt;enumeration value="MedicalExcuse"/>
 *     &lt;enumeration value="NoExemption"/>
 *     &lt;enumeration value="OnHold"/>
 *     &lt;enumeration value="ParentExemption"/>
 *     &lt;enumeration value="Pending"/>
 *     &lt;enumeration value="SecurityCancellation"/>
 *     &lt;enumeration value="Waiver"/>
 *     &lt;enumeration value="WithheldbyExaminee"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScoreExclusionReasonCodeType")
@XmlEnum
public enum ScoreExclusionReasonCodeType {

    @XmlEnumValue("Absent")
    ABSENT("Absent"),
    @XmlEnumValue("AdministrativeCancellation")
    ADMINISTRATIVE_CANCELLATION("AdministrativeCancellation"),
    @XmlEnumValue("AdministrativeDiscretion")
    ADMINISTRATIVE_DISCRETION("AdministrativeDiscretion"),
    @XmlEnumValue("ExamineeCancellation")
    EXAMINEE_CANCELLATION("ExamineeCancellation"),
    @XmlEnumValue("ExtraordinaryCircumstances")
    EXTRAORDINARY_CIRCUMSTANCES("ExtraordinaryCircumstances"),
    @XmlEnumValue("MedicalExcuse")
    MEDICAL_EXCUSE("MedicalExcuse"),
    @XmlEnumValue("NoExemption")
    NO_EXEMPTION("NoExemption"),
    @XmlEnumValue("OnHold")
    ON_HOLD("OnHold"),
    @XmlEnumValue("ParentExemption")
    PARENT_EXEMPTION("ParentExemption"),
    @XmlEnumValue("Pending")
    PENDING("Pending"),
    @XmlEnumValue("SecurityCancellation")
    SECURITY_CANCELLATION("SecurityCancellation"),
    @XmlEnumValue("Waiver")
    WAIVER("Waiver"),
    @XmlEnumValue("WithheldbyExaminee")
    WITHHELDBY_EXAMINEE("WithheldbyExaminee");
    private final String value;

    ScoreExclusionReasonCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScoreExclusionReasonCodeType fromValue(String v) {
        for (ScoreExclusionReasonCodeType c: ScoreExclusionReasonCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
