//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SessionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SessionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FullYear"/>
 *     &lt;enumeration value="Semester"/>
 *     &lt;enumeration value="Trimester"/>
 *     &lt;enumeration value="Quarter"/>
 *     &lt;enumeration value="Quinmester"/>
 *     &lt;enumeration value="MiniTerm"/>
 *     &lt;enumeration value="SummerSession"/>
 *     &lt;enumeration value="Intersession"/>
 *     &lt;enumeration value="LongSession"/>
 *     &lt;enumeration value="FallSession"/>
 *     &lt;enumeration value="FourOneFourPlan"/>
 *     &lt;enumeration value="Continuous"/>
 *     &lt;enumeration value="DiffersByProgram"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="TwelveMonth"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SessionTypeType")
@XmlEnum
public enum SessionTypeType {

    @XmlEnumValue("FullYear")
    FULL_YEAR("FullYear"),
    @XmlEnumValue("Semester")
    SEMESTER("Semester"),
    @XmlEnumValue("Trimester")
    TRIMESTER("Trimester"),
    @XmlEnumValue("Quarter")
    QUARTER("Quarter"),
    @XmlEnumValue("Quinmester")
    QUINMESTER("Quinmester"),
    @XmlEnumValue("MiniTerm")
    MINI_TERM("MiniTerm"),
    @XmlEnumValue("SummerSession")
    SUMMER_SESSION("SummerSession"),
    @XmlEnumValue("Intersession")
    INTERSESSION("Intersession"),
    @XmlEnumValue("LongSession")
    LONG_SESSION("LongSession"),
    @XmlEnumValue("FallSession")
    FALL_SESSION("FallSession"),
    @XmlEnumValue("FourOneFourPlan")
    FOUR_ONE_FOUR_PLAN("FourOneFourPlan"),
    @XmlEnumValue("Continuous")
    CONTINUOUS("Continuous"),
    @XmlEnumValue("DiffersByProgram")
    DIFFERS_BY_PROGRAM("DiffersByProgram"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("TwelveMonth")
    TWELVE_MONTH("TwelveMonth");
    private final String value;

    SessionTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SessionTypeType fromValue(String v) {
        for (SessionTypeType c: SessionTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
