//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureSourceCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SignatureSourceCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;minLength value="1"/>
 *     &lt;enumeration value="Student"/>
 *     &lt;enumeration value="Borrower"/>
 *     &lt;enumeration value="Cosigner1"/>
 *     &lt;enumeration value="Cosigner2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SignatureSourceCodeType")
@XmlEnum
public enum SignatureSourceCodeType {

    @XmlEnumValue("Student")
    STUDENT("Student"),
    @XmlEnumValue("Borrower")
    BORROWER("Borrower"),
    @XmlEnumValue("Cosigner1")
    COSIGNER_1("Cosigner1"),
    @XmlEnumValue("Cosigner2")
    COSIGNER_2("Cosigner2");
    private final String value;

    SignatureSourceCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SignatureSourceCodeType fromValue(String v) {
        for (SignatureSourceCodeType c: SignatureSourceCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
