//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SponsorTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SponsorTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Parent"/>
 *     &lt;enumeration value="Spouse"/>
 *     &lt;enumeration value="Relative"/>
 *     &lt;enumeration value="USCompany"/>
 *     &lt;enumeration value="ForeignCompany"/>
 *     &lt;enumeration value="USGovernment"/>
 *     &lt;enumeration value="ForeignGovernment"/>
 *     &lt;enumeration value="Organization"/>
 *     &lt;enumeration value="Institution"/>
 *     &lt;enumeration value="Self"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SponsorTypeType")
@XmlEnum
public enum SponsorTypeType {

    @XmlEnumValue("Parent")
    PARENT("Parent"),
    @XmlEnumValue("Spouse")
    SPOUSE("Spouse"),
    @XmlEnumValue("Relative")
    RELATIVE("Relative"),
    @XmlEnumValue("USCompany")
    US_COMPANY("USCompany"),
    @XmlEnumValue("ForeignCompany")
    FOREIGN_COMPANY("ForeignCompany"),
    @XmlEnumValue("USGovernment")
    US_GOVERNMENT("USGovernment"),
    @XmlEnumValue("ForeignGovernment")
    FOREIGN_GOVERNMENT("ForeignGovernment"),
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),
    @XmlEnumValue("Institution")
    INSTITUTION("Institution"),
    @XmlEnumValue("Self")
    SELF("Self"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    SponsorTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SponsorTypeType fromValue(String v) {
        for (SponsorTypeType c: SponsorTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
