//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Test Score Type
 * 
 * <p>Java class for TestScoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestScoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScoreValue" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreValueType"/>
 *         &lt;element name="TestScoreMethod" type="{urn:org:pesc:core:CoreMain:v1.12.0}TestScoreMethodType" minOccurs="0"/>
 *         &lt;element name="ScoreRevisedIndicator" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreRevisedIndicatorType" minOccurs="0"/>
 *         &lt;element name="ScoreInvalidatedIndicator" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreInvalidatedIndicatorType" minOccurs="0"/>
 *         &lt;element name="ScoreSelfreportedIndicator" type="{urn:org:pesc:core:CoreMain:v1.12.0}ScoreSelfreportedIndicatorType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.12.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestScoreType", propOrder = {
    "scoreValue",
    "testScoreMethod",
    "scoreRevisedIndicator",
    "scoreInvalidatedIndicator",
    "scoreSelfreportedIndicator",
    "noteMessage"
})
public class TestScoreType {

    @XmlElement(name = "ScoreValue", required = true)
    protected String scoreValue;
    @XmlElement(name = "TestScoreMethod")
    protected TestScoreMethodType testScoreMethod;
    @XmlElement(name = "ScoreRevisedIndicator")
    protected Boolean scoreRevisedIndicator;
    @XmlElement(name = "ScoreInvalidatedIndicator")
    protected Boolean scoreInvalidatedIndicator;
    @XmlElement(name = "ScoreSelfreportedIndicator")
    protected Boolean scoreSelfreportedIndicator;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the scoreValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreValue() {
        return scoreValue;
    }

    /**
     * Sets the value of the scoreValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreValue(String value) {
        this.scoreValue = value;
    }

    /**
     * Gets the value of the testScoreMethod property.
     * 
     * @return
     *     possible object is
     *     {@link TestScoreMethodType }
     *     
     */
    public TestScoreMethodType getTestScoreMethod() {
        return testScoreMethod;
    }

    /**
     * Sets the value of the testScoreMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestScoreMethodType }
     *     
     */
    public void setTestScoreMethod(TestScoreMethodType value) {
        this.testScoreMethod = value;
    }

    /**
     * Gets the value of the scoreRevisedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScoreRevisedIndicator() {
        return scoreRevisedIndicator;
    }

    /**
     * Sets the value of the scoreRevisedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScoreRevisedIndicator(Boolean value) {
        this.scoreRevisedIndicator = value;
    }

    /**
     * Gets the value of the scoreInvalidatedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScoreInvalidatedIndicator() {
        return scoreInvalidatedIndicator;
    }

    /**
     * Sets the value of the scoreInvalidatedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScoreInvalidatedIndicator(Boolean value) {
        this.scoreInvalidatedIndicator = value;
    }

    /**
     * Gets the value of the scoreSelfreportedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScoreSelfreportedIndicator() {
        return scoreSelfreportedIndicator;
    }

    /**
     * Sets the value of the scoreSelfreportedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScoreSelfreportedIndicator(Boolean value) {
        this.scoreSelfreportedIndicator = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
