//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 05:40:47 PM PST 
//


package org.pesc.core.coremain.v1_12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransmissionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransmissionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Duplicate"/>
 *     &lt;enumeration value="MutuallyDefined"/>
 *     &lt;enumeration value="Original"/>
 *     &lt;enumeration value="Reissue"/>
 *     &lt;enumeration value="Replace"/>
 *     &lt;enumeration value="Resubmission"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransmissionTypeType")
@XmlEnum
public enum TransmissionTypeType {

    @XmlEnumValue("Duplicate")
    DUPLICATE("Duplicate"),
    @XmlEnumValue("MutuallyDefined")
    MUTUALLY_DEFINED("MutuallyDefined"),
    @XmlEnumValue("Original")
    ORIGINAL("Original"),
    @XmlEnumValue("Reissue")
    REISSUE("Reissue"),
    @XmlEnumValue("Replace")
    REPLACE("Replace"),
    @XmlEnumValue("Resubmission")
    RESUBMISSION("Resubmission");
    private final String value;

    TransmissionTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransmissionTypeType fromValue(String v) {
        for (TransmissionTypeType c: TransmissionTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
