CREATE TABLE `organization_entity_code` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `entity_code` TINYINT(2) NOT NULL COMMENT 'Entity Code: 0 - UNDEFINED, 1 - INSTITUTION, 2 - ACADEMIC AGENCY, 3 - SERVICE PROVIDER, ...',
  `description` TEXT NOT NULL,
  
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created Time',
  `modified_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Updated Time',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;