directory-db:
  build: ./target/docker/database
  ports:
   - "5432:5432"
  container_name: directory-db

directory-server:
  image: edex/directory-server
  ports:
   - "8080:8080"
   - "8000:8000"
  extra_hosts:
   - directory-db:172.17.0.1
  environment:
   - SPRING_PROFILES_ACTIVE=qa
   - DB_SERVER=directory-db
   - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
   - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME}
   - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
